export interface Joke {
  id: number
  delivery: string
  punchline: string
}

export const JOKES: Joke[] = [
  { id: 1, delivery: "What do you call a factory that makes okay products?", punchline: "A satisfactory." },
  { id: 2, delivery: "I told my wife she should embrace her mistakes.", punchline: "She gave me a hug." },
  { id: 3, delivery: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field." },
  { id: 4, delivery: "Why can’t you hear a pterodactyl go to the bathroom?", punchline: "Because the “P” is silent." },
  { id: 5, delivery: "What’s orange and sounds like a parrot?", punchline: "A carrot." },
  { id: 6, delivery: "I used to play piano by ear.", punchline: "Now I use my hands." },
  { id: 7, delivery: "Why did the coffee file a police report?", punchline: "It got mugged." },
  { id: 8, delivery: "Why don’t eggs tell jokes?", punchline: "They’d crack each other up." },
  { id: 9, delivery: "I only know 25 letters of the alphabet.", punchline: "I don’t know y." },
  { id: 10, delivery: "Why did the golfer bring an extra pair of pants?", punchline: "In case he got a hole in one." },
  { id: 11, delivery: "What do you call fake spaghetti?", punchline: "An impasta." },
  { id: 12, delivery: "How do you organize a space party?", punchline: "You planet." },
  { id: 13, delivery: "What did one wall say to the other wall?", punchline: "I’ll meet you at the corner." },
  { id: 14, delivery: "I asked the librarian if the library had books on paranoia.", punchline: "She whispered, “They’re right behind you.”" },
  { id: 15, delivery: "Why did the math book look sad?", punchline: "It had too many problems." },
  { id: 16, delivery: "What do you call a fish wearing a bowtie?", punchline: "So-fish-ticated." },
  { id: 17, delivery: "Why don’t skeletons fight each other?", punchline: "They don’t have the guts." },
  { id: 18, delivery: "I used to be addicted to soap.", punchline: "But I’m clean now." },
  { id: 19, delivery: "Why did the bicycle fall over?", punchline: "It was two-tired." },
  { id: 20, delivery: "What do you call cheese that isn’t yours?", punchline: "Nacho cheese." },
  { id: 21, delivery: "Did you hear about the claustrophobic astronaut?", punchline: "He needed a little space." },
  { id: 22, delivery: "I don’t trust stairs.", punchline: "They’re always up to something." },
  { id: 23, delivery: "Why did the photo go to jail?", punchline: "It was framed." },
  { id: 24, delivery: "What’s brown and sticky?", punchline: "A stick." },
  { id: 25, delivery: "Why did the man get hit by a bike every day?", punchline: "He was stuck in a vicious cycle." },
  { id: 26, delivery: "How do you make a tissue dance?", punchline: "Put a little boogie in it." },
  { id: 27, delivery: "Why did the cookie go to the hospital?", punchline: "Because it felt crumby." },
  { id: 28, delivery: "I used to be a baker.", punchline: "I couldn’t make enough dough." },
  { id: 29, delivery: "Why can’t a leopard hide?", punchline: "He’s always spotted." },
  { id: 30, delivery: "What did the ocean say to the shore?", punchline: "Nothing, it just waved." },
  { id: 31, delivery: "Why do seagulls fly over the sea?", punchline: "Because if they flew over the bay, they’d be bagels." },
  { id: 32, delivery: "I’m reading a book about anti-gravity.", punchline: "It’s impossible to put down." },
  { id: 33, delivery: "Why did the tomato blush?", punchline: "It saw the salad dressing." },
  { id: 34, delivery: "What do you call a belt made of watches?", punchline: "A waist of time." },
  { id: 35, delivery: "Why did the computer go to the doctor?", punchline: "It caught a virus." },
  { id: 36, delivery: "What do you call a pile of cats?", punchline: "A meowtain." },
  { id: 37, delivery: "I only tell uranium jokes.", punchline: "They’re always splitting sides." },
  { id: 38, delivery: "Why did the stadium get hot?", punchline: "All the fans left." },
  { id: 39, delivery: "How do you find Will Smith in the snow?", punchline: "Look for fresh prints." },
  { id: 40, delivery: "What do you call a sleeping bull?", punchline: "A bulldozer." },
  { id: 41, delivery: "Why don’t oysters donate to charity?", punchline: "Because they’re shellfish." },
  { id: 42, delivery: "What do you call a dinosaur with an extensive vocabulary?", punchline: "A thesaurus." },
  { id: 43, delivery: "Why did the broom arrive late?", punchline: "It swept in." },
  { id: 44, delivery: "I asked my dog what’s two minus two.", punchline: "He said nothing." },
  { id: 45, delivery: "Why are elevator jokes so classic?", punchline: "They work on many levels." },
  { id: 46, delivery: "I used to hate facial hair.", punchline: "But then it grew on me." },
  { id: 47, delivery: "What do you call a cold dog?", punchline: "A chili dog." },
  { id: 48, delivery: "Why did the man name his dogs Rolex and Timex?", punchline: "They were watch dogs." },
  { id: 49, delivery: "What do you call a bee that can’t make up its mind?", punchline: "A may-bee." },
  { id: 50, delivery: "Why can’t your nose be 12 inches long?", punchline: "Because then it would be a foot." },
  { id: 51, delivery: "What did the buffalo say to his son when he left for college?", punchline: "Bison." },
  { id: 52, delivery: "Why did the banana go to the doctor?", punchline: "It wasn’t peeling well." },
  { id: 53, delivery: "What’s Forrest Gump’s email password?", punchline: "1forrest1." },
  { id: 54, delivery: "How do you make holy water?", punchline: "You boil the hell out of it." },
  { id: 55, delivery: "Why did the scarecrow get promoted?", punchline: "He was outstanding in his field—again." },
  { id: 56, delivery: "Why did the barber win the race?", punchline: "He knew a shortcut." },
  { id: 57, delivery: "Why did the belt get arrested?", punchline: "It held up a pair of pants." },
  { id: 58, delivery: "What’s brown, hairy, and wears sunglasses?", punchline: "A coconut on vacation." },
  { id: 59, delivery: "Why did the candle quit his job?", punchline: "He was burned out." },
  { id: 60, delivery: "What do you call a nervous javelin thrower?", punchline: "Shakespeare." },
  { id: 61, delivery: "What do you call a boomerang that doesn’t come back?", punchline: "A stick." },
  { id: 62, delivery: "Why did the grape stop in the road?", punchline: "It ran out of juice." },
  { id: 63, delivery: "Why are ghosts bad at lying?", punchline: "You can see right through them." },
  { id: 64, delivery: "What do you call an alligator in a vest?", punchline: "An investigator." },
  { id: 65, delivery: "I told my doctor I broke my arm in two places.", punchline: "He told me to stop going to those places." },
  { id: 66, delivery: "Why don’t crabs give to charity?", punchline: "They’re a little shellfish, too." },
  { id: 67, delivery: "Why did the cyclist keep yawning?", punchline: "He was two-tired—again." },
  { id: 68, delivery: "Why did the cow become an astronaut?", punchline: "To see the moooon." },
  { id: 69, delivery: "Why did the fisherman get kicked out of class?", punchline: "He was net-working." },
  { id: 70, delivery: "What do you call a line of men waiting for a haircut?", punchline: "A barberqueue." },
  { id: 71, delivery: "Why did the smartphone wear glasses?", punchline: "It lost its contacts." },
  { id: 72, delivery: "What’s the best way to watch a fly fishing tournament?", punchline: "Live stream." },
  { id: 73, delivery: "Why don’t some couples go to the gym?", punchline: "Because some relationships don’t work out." },
  { id: 74, delivery: "Why did the scarecrow get a raise?", punchline: "His field performance was outstanding." },
  { id: 75, delivery: "What do you call an apology written in dots and dashes?", punchline: "Remorse code." },
  { id: 76, delivery: "Why did the picture go to prison?", punchline: "It was framed—still guilty." },
  { id: 77, delivery: "Why did the chef get locked out?", punchline: "He lost his thyme." },
  { id: 78, delivery: "I used to be a gymnast.", punchline: "It didn’t work out—too many somersaults." },
  { id: 79, delivery: "What do you call a very small valentine?", punchline: "A valen-tiny." },
  { id: 80, delivery: "Why did the musician get kicked out of the bakery?", punchline: "He kept trying to steal the notes." },
  { id: 81, delivery: "Why did the gardener plant a light bulb?", punchline: "He wanted to grow a power plant." },
  { id: 82, delivery: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman." },
  { id: 83, delivery: "How do you catch a whole school of fish?", punchline: "With bookworms." },
  { id: 84, delivery: "Why did the cat sit on the computer?", punchline: "It wanted to keep an eye on the mouse." },
  { id: 85, delivery: "What do you call a camel with no humps?", punchline: "Humphrey." },
  { id: 86, delivery: "Why did the man bring a spoon to the fight?", punchline: "He wanted to stir things up." },
  { id: 87, delivery: "Why did the hipster burn his tongue?", punchline: "He drank his coffee before it was cool." },
  { id: 88, delivery: "What do you call a sheep with no legs?", punchline: "A cloud." },
  { id: 89, delivery: "Why did the banker switch careers?", punchline: "He lost interest." },
  { id: 90, delivery: "Why did the clock get in trouble at school?", punchline: "It tocked back to the teacher." },
  { id: 91, delivery: "What do you call a fish with no eyes?", punchline: "Fsh." },
  { id: 92, delivery: "Why was the broom so tired?", punchline: "It had a sweeping schedule." },
  { id: 93, delivery: "What did the zero say to the eight?", punchline: "Nice belt." },
  { id: 94, delivery: "Why did the turtle cross the road?", punchline: "To get to the shell station." },
  { id: 95, delivery: "Why did the music teacher need a ladder?", punchline: "To reach the high notes." },
  { id: 96, delivery: "Why did the vampire read the newspaper?", punchline: "He heard it had great circulation." },
  { id: 97, delivery: "What do you call a can opener that doesn’t work?", punchline: "A can’t opener." },
  { id: 98, delivery: "Why did the lettuce win the race?", punchline: "Because it was a-head." },
  { id: 99, delivery: "How do you comfort a grammar teacher?", punchline: "There, their, they’re." },
  { id: 100, delivery: "I told my kids we’re having tacos for dinner.", punchline: "They said, “That’s nacho decision.” I said, “Yes it is.”" },
  { id: 101, delivery: "Why did the developer go broke?", punchline: "Because he used up all his cache." },
  { id: 102, delivery: "Why did the PowerPoint presentation cross the road?", punchline: "To get to the next slide." },
  { id: 103, delivery: "What do you call a dad who makes memes?", punchline: "A pun-fluencer." },
  { id: 104, delivery: "Why was the computer cold?", punchline: "It left its Windows open." },
  { id: 105, delivery: "What do you call a lazy kangaroo?", punchline: "A pouch potato." },
  { id: 106, delivery: "Why did the AI go to therapy?", punchline: "It had deep learning issues." },
  { id: 107, delivery: "Why don’t programmers like nature?", punchline: "Too many bugs." },
  { id: 108, delivery: "What’s a pirate’s least favorite letter?", punchline: "Dear Sir or Madam…" },
  { id: 109, delivery: "Why did the chicken join a band?", punchline: "Because it already had drumsticks." },
  { id: 110, delivery: "How do robots pay for things?", punchline: "With cache or crypto." },
  { id: 111, delivery: "Why did the office printer file a complaint?", punchline: "It was tired of being jammed." },
  { id: 112, delivery: "What do you call a dad who tells jokes about pizza?", punchline: "A pun-za lover." },
  { id: 113, delivery: "Why did the spreadsheet go to therapy?", punchline: "It had too many cells." },
  { id: 114, delivery: "Why don’t you ever play hide and seek with mountains?", punchline: "They always peak." },
  { id: 115, delivery: "How does the internet sneeze?", punchline: "Ah-choo-tube!" },
  { id: 116, delivery: "Why was the smartphone acting so smart?", punchline: "It finally got an upgrade." },
  { id: 117, delivery: "Why did the boss bring a pencil to the meeting?", punchline: "To draw conclusions." },
  { id: 118, delivery: "Why was the broom late to work?", punchline: "It overswept." },
  { id: 119, delivery: "What do you call a group of disorganized cats?", punchline: "A cat-astrophe." },
  { id: 120, delivery: "Why did the Wi-Fi break up with the router?", punchline: "The connection was lost." },
  { id: 121, delivery: "How do cows stay up to date?", punchline: "They read the moos-paper." },
  { id: 122, delivery: "Why did the gamer get kicked out of the bar?", punchline: "He was pressing “escape.”" },
  { id: 123, delivery: "Why did the dad put his money in the blender?", punchline: "He wanted liquid assets." },
  { id: 124, delivery: "How does the moon cut his hair?", punchline: "Eclipse it." },
  { id: 125, delivery: "Why did the employee bring a ladder to work?", punchline: "The boss said promotions were up." },
  { id: 126, delivery: "Why did the clock get sent home early?", punchline: "It needed some downtime." },
  { id: 127, delivery: "What’s a cat’s favorite social media platform?", punchline: "Insta-purr-gram." },
  { id: 128, delivery: "Why did the dad start a podcast?", punchline: "He wanted to share his sound advice." },
  { id: 129, delivery: "Why did the email break up with the inbox?", punchline: "Too much spam in the relationship." },
  { id: 130, delivery: "Why do vampires use mouthwash?", punchline: "Because they have bat breath." },
  { id: 131, delivery: "What do you call a bear with no teeth?", punchline: "A gummy bear." },
  { id: 132, delivery: "Why did the employee sit on the clock?", punchline: "He wanted to be on time." },
  { id: 133, delivery: "Why did the dad bring string to the bar?", punchline: "He wanted to tie one on." },
  { id: 134, delivery: "Why was the selfie so confident?", punchline: "It had the best angle on life." },
  { id: 135, delivery: "What did one keyboard say to the other?", punchline: "You’re my type." },
  { id: 136, delivery: "Why did the calendar look depressed?", punchline: "Its days were numbered." },
  { id: 137, delivery: "Why did the coffee shop close early?", punchline: "A latte problems." },
  { id: 138, delivery: "Why did the dad stare at the orange juice carton?", punchline: "It said, “concentrate.”" },
  { id: 139, delivery: "What do you call someone who takes care of chickens?", punchline: "A chicken tender." },
  { id: 140, delivery: "Why do astronauts use social media?", punchline: "To get more space followers." },
  { id: 141, delivery: "Why did the dad join a coding bootcamp?", punchline: "He heard it was a class act." },
  { id: 142, delivery: "How does a penguin build its house?", punchline: "Igloos it together." },
  { id: 143, delivery: "What’s a skeleton’s favorite snack?", punchline: "Spare ribs." },
  { id: 144, delivery: "Why did the tomato turn red?", punchline: "It saw the ketchup bottle." },
  { id: 145, delivery: "Why did the spreadsheet cross the road?", punchline: "To get to the other column." },
  { id: 146, delivery: "How do you tell if a dad joke is a dad joke?", punchline: "It becomes apparent." },
  { id: 147, delivery: "Why did the gamer sit so close to the TV?", punchline: "He wanted to play it by ear." },
  { id: 148, delivery: "What do you call a singing laptop?", punchline: "A Dell." },
  { id: 149, delivery: "Why did the password go to jail?", punchline: "It was too weak." },
  { id: 150, delivery: "What’s a dad’s favorite instrument?", punchline: "The dad-bodhran." },
  { id: 151, delivery: "Why was the broom promoted?", punchline: "It swept the competition." },
  { id: 152, delivery: "What’s the best way to make holy water?", punchline: "You boil the hell out of it." },
  { id: 153, delivery: "Why did the dad bring a battery to dinner?", punchline: "He wanted a charged atmosphere." },
  { id: 154, delivery: "Why do bees have sticky hair?", punchline: "They use honeycombs." },
  { id: 155, delivery: "Why did the laptop marry the mouse?", punchline: "They clicked." },
  { id: 156, delivery: "What do you call a fake noodle?", punchline: "An impasta—still funny the second time." },
  { id: 157, delivery: "Why did the dad refuse to play cards in the jungle?", punchline: "Too many cheetahs." },
  { id: 158, delivery: "Why did the skeleton start a band?", punchline: "He had the bones for it." },
  { id: 159, delivery: "Why did the office worker sit on a stapler?", punchline: "To stay connected." },
  { id: 160, delivery: "What do you call an apology from a robot?", punchline: "Error in judgment." },
  { id: 161, delivery: "Why did the tech support guy quit?", punchline: "He lost his drive." },
  { id: 162, delivery: "Why did the fortune cookie go to therapy?", punchline: "It couldn’t handle being broken inside." },
  { id: 163, delivery: "What did one volcano say to the other?", punchline: "I lava you." },
  { id: 164, delivery: "Why did the math teacher love parks?", punchline: "All the natural logs." },
  { id: 165, delivery: "Why did the dad sit next to the Wi-Fi router?", punchline: "He wanted a better connection with his kids." },
  { id: 166, delivery: "Why did the penguin drive so fast?", punchline: "He was trying to break the ice." },
  { id: 167, delivery: "Why do fathers take extra socks to the golf course?", punchline: "In case they get a hole in one." },
  { id: 168, delivery: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies!" },
  { id: 169, delivery: "What’s a dad’s favorite time?", punchline: "6:30 — hands down." },
  { id: 170, delivery: "Why did the gamer sleep under his desk?", punchline: "He wanted to save his progress." },
  { id: 171, delivery: "Why was the database so calm?", punchline: "It had ACID properties." },
  { id: 172, delivery: "Why did the dad start a gardening blog?", punchline: "He wanted to turnip the engagement." },
  { id: 173, delivery: "What do you call a boomerang that won’t come back?", punchline: "A stick — still classic." },
  { id: 174, delivery: "Why did the employee stare at his orange juice?", punchline: "Because it said “concentrate.” (Dad jokes recycle.)" },
  { id: 175, delivery: "Why did the meme go to school?", punchline: "To become a little more relatable." },
  { id: 176, delivery: "Why did the dad refuse to get new shoes?", punchline: "His sole was still good." },
  { id: 177, delivery: "Why do programmers prefer dark mode?", punchline: "Because light attracts bugs." },
  { id: 178, delivery: "Why did the dad sit in the corner at the restaurant?", punchline: "He wanted to have a side order." },
  { id: 179, delivery: "Why was the broom the best employee?", punchline: "It always swept up after itself." },
  { id: 180, delivery: "What do you call a broken can opener?", punchline: "A can’t opener." },
  { id: 181, delivery: "Why did the dad take a ladder to the bar?", punchline: "He heard the drinks were on the house." },
  { id: 182, delivery: "Why did the baker stop making donuts?", punchline: "He got tired of the hole business." },
  { id: 183, delivery: "Why did the dad take his clock to the vet?", punchline: "It had ticks." },
  { id: 184, delivery: "Why did the website go to the doctor?", punchline: "It had a bad case of cookies." },
  { id: 185, delivery: "Why do dads love elevators?", punchline: "Because they’re uplifting." },
  { id: 186, delivery: "Why did the dad get kicked out of the music store?", punchline: "He couldn’t Handel it." },
  { id: 187, delivery: "Why did the cloud get invited to parties?", punchline: "Because it was the life of the server." },
  { id: 188, delivery: "What do you call a fish that tells jokes?", punchline: "A clownfish." },
  { id: 189, delivery: "Why did the dad take a nap on the keyboard?", punchline: "He needed a bit of rest control." },
  { id: 190, delivery: "Why did the phone go to art school?", punchline: "It wanted to improve its selfies." },
  { id: 191, delivery: "Why was the gardener so good at math?", punchline: "He knew how to multiply." },
  { id: 192, delivery: "Why did the dad throw his alarm clock out the window?", punchline: "He wanted to see time fly." },
  { id: 193, delivery: "What do you call an iPhone that isn’t kidding around?", punchline: "Dead Siri-ous." },
  { id: 194, delivery: "What did the left eye say to the right eye?", punchline: "Between you and me, something smells." },
  { id: 195, delivery: "Why did the dad install a skylight?", punchline: "To let a little light-heartedness in." },
  { id: 196, delivery: "What do you call a cow that plays the guitar?", punchline: "A moo-sician." },
  { id: 197, delivery: "Why did the employee bring toilet paper to the meeting?", punchline: "It was a crapshoot." },
  { id: 198, delivery: "Why did the dad buy new socks?", punchline: "He wanted to step up his game." },
  { id: 199, delivery: "Why did the dog sit in the shade?", punchline: "Because it didn’t want to be a hot dog." },
  { id: 200, delivery: "What do you call a group of dads telling jokes?", punchline: "A pun-demic." },
  { id: 201, delivery: "Why did the developer stay home from work?", punchline: "He didn’t feel up to code." },
  { id: 202, delivery: "Why did the cloud get nervous at the presentation?", punchline: "Too much pressure in the atmosphere." },
  { id: 203, delivery: "What do you call a sleeping computer?", punchline: "A power nap-top." },
  { id: 204, delivery: "Why did the gamer bring a broom to the tournament?", punchline: "To sweep the competition." },
  { id: 205, delivery: "What’s a dad’s favorite kind of music?", punchline: "Pop." },
  { id: 206, delivery: "Why did the stapler break up with the paper?", punchline: "It found someone more binding." },
  { id: 207, delivery: "How do you make a computer laugh?", punchline: "Tell it a byte-sized joke." },
  { id: 208, delivery: "Why did the dad put his car in the oven?", punchline: "He wanted a hot rod." },
  { id: 209, delivery: "Why did the tech startup hire a magician?", punchline: "To make their funding disappear." },
  { id: 210, delivery: "Why was the computer so good at singing?", punchline: "It had perfect pitch." },
  { id: 211, delivery: "Why did the dad bring his watch to the bar?", punchline: "He wanted to have a good time." },
  { id: 212, delivery: "What’s a hacker’s favorite kind of tea?", punchline: "URL grey." },
  { id: 213, delivery: "Why did the dad start whispering around his Wi-Fi?", punchline: "He didn’t want to make a scene." },
  { id: 214, delivery: "Why did the robot go on a diet?", punchline: "Too many bytes." },
  { id: 215, delivery: "Why did the dad refuse to play poker with the jungle animals?", punchline: "He was afraid of cheetahs." },
  { id: 216, delivery: "How does a cat end a fight?", punchline: "With a hiss-truce." },
  { id: 217, delivery: "Why was the broom a terrible roommate?", punchline: "It swept under the rug." },
  { id: 218, delivery: "Why do dads always win hide and seek?", punchline: "Because good dads are outstanding in their field." },
  { id: 219, delivery: "Why did the bicycle stand on its own?", punchline: "It was two-tired of falling over." },
  { id: 220, delivery: "Why did the computer take a nap?", punchline: "It needed to reboot." },
  { id: 221, delivery: "Why don’t we see elephants hiding in trees?", punchline: "Because they’re so good at it." },
  { id: 222, delivery: "Why was the photo always so calm?", punchline: "It was well composed." },
  { id: 223, delivery: "How do you fix a broken pizza?", punchline: "With tomato paste." },
  { id: 224, delivery: "Why do bees hum?", punchline: "Because they don’t know the words." },
  { id: 225, delivery: "Why was the dad staring at the can of orange juice?", punchline: "Because it said “concentrate” — again." },
  { id: 226, delivery: "Why did the dad’s joke go to therapy?", punchline: "It couldn’t find its punchline." },
  { id: 227, delivery: "What’s a dad’s favorite kind of exercise?", punchline: "Diddly-squats." },
  { id: 228, delivery: "Why did the scarecrow become a successful influencer?", punchline: "He was outstanding in his field — and had great reach." },
  { id: 229, delivery: "What do you call a sleeping dinosaur?", punchline: "A dino-snore." },
  { id: 230, delivery: "Why was the Wi-Fi acting up?", punchline: "It needed a router reboot-ation." },
  { id: 231, delivery: "How do cows send secret messages?", punchline: "Steganomo-graphy." },
  { id: 232, delivery: "What do you call a dad who tells jokes while grilling?", punchline: "A pun-flame thrower." },
  { id: 233, delivery: "Why did the dad bring an umbrella to the barbecue?", punchline: "For the drizzle." },
  { id: 234, delivery: "Why did the gamer’s chair break?", punchline: "Too much sitting XP." },
  { id: 235, delivery: "Why did the refrigerator win employee of the month?", punchline: "It kept its cool." },
  { id: 236, delivery: "Why did the office computer sing?", punchline: "It had too many tabs open and needed to vent." },
  { id: 237, delivery: "Why did the dad take up fishing?", punchline: "He found it reel-axing." },
  { id: 238, delivery: "Why do ducks have feathers?", punchline: "To cover their butt-quacks." },
  { id: 239, delivery: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies! (Yes, it’s still funny.)" },
  { id: 240, delivery: "Why did the robot break up with its girlfriend?", punchline: "She had too many parameters." },
  { id: 241, delivery: "Why did the dad put his keys in the fridge?", punchline: "He wanted a cool start to his day." },
  { id: 242, delivery: "Why did the pancake apply for a job?", punchline: "It wanted to flip its career." },
  { id: 243, delivery: "Why did the sandwich go to the gym?", punchline: "To get shredded." },
  { id: 244, delivery: "How do trees access the internet?", punchline: "They log in." },
  { id: 245, delivery: "What do you call a belt made of money?", punchline: "A waist of cash." },
  { id: 246, delivery: "Why did the dad sit on the remote?", punchline: "He wanted to control himself." },
  { id: 247, delivery: "Why was the cloud so confident?", punchline: "It had plenty of self-storage." },
  { id: 248, delivery: "Why did the math teacher open a bakery?", punchline: "She was great with pie charts." },
  { id: 249, delivery: "Why did the skeleton go to the party alone?", punchline: "He had no body to go with." },
  { id: 250, delivery: "Why did the smartphone go to the dentist?", punchline: "It had Bluetooth." },
  { id: 251, delivery: "Why do dads make terrible secret agents?", punchline: "They always crack under pun-pressure." },
  { id: 252, delivery: "Why did the car apply for a job?", punchline: "It wanted to get a drive in life." },
  { id: 253, delivery: "Why do frogs never get stressed?", punchline: "They eat what bugs them." },
  { id: 254, delivery: "Why did the programmer always stay calm?", punchline: "He had exception handling." },
  { id: 255, delivery: "Why did the chef quit his job?", punchline: "He couldn’t make enough dough." },
  { id: 256, delivery: "What’s a skeleton’s least favorite room?", punchline: "The living room." },
  { id: 257, delivery: "Why did the dad bring a ruler to bed?", punchline: "To see how long he slept." },
  { id: 258, delivery: "Why was the baby strawberry crying?", punchline: "Its parents were in a jam." },
  { id: 259, delivery: "What’s a cat’s favorite color?", punchline: "Purr-ple." },
  { id: 260, delivery: "Why did the light bulb break up with the switch?", punchline: "There was no spark." },
  { id: 261, delivery: "What’s a computer’s favorite snack?", punchline: "Microchips." },
  { id: 262, delivery: "Why did the gardener quit?", punchline: "His celery wasn’t high enough." },
  { id: 263, delivery: "Why did the banana go to therapy?", punchline: "It couldn’t peel with life." },
  { id: 264, delivery: "What did the fish say when it hit the wall?", punchline: "Dam." },
  { id: 265, delivery: "Why was the cookie so sad?", punchline: "Because its mom was a wafer too long." },
  { id: 266, delivery: "Why was the dad’s belt arrested?", punchline: "For holding up a pair of pants — again." },
  { id: 267, delivery: "Why was the broom late?", punchline: "It overswept — classic." },
  { id: 268, delivery: "What do you call a sheep that does karate?", punchline: "Lamb chop." },
  { id: 269, delivery: "Why did the snowman look in the bag of carrots?", punchline: "He was picking his nose." },
  { id: 270, delivery: "What do you call a factory that makes OK products?", punchline: "A satisfactory — still checks out." },
  { id: 271, delivery: "Why did the dad join the choir?", punchline: "He wanted to raise the baritone." },
  { id: 272, delivery: "Why do ducks make great detectives?", punchline: "They always quack the case." },
  { id: 273, delivery: "Why did the bicycle need therapy?", punchline: "It was tired of being walked all over." },
  { id: 274, delivery: "What do you call an indecisive bee?", punchline: "A may-bee." },
  { id: 275, delivery: "Why did the dad stare at his can of soda?", punchline: "Because it was pop art." },
  { id: 276, delivery: "Why did the scarecrow become a DJ?", punchline: "He was outstanding in his field — and had sick beats." },
  { id: 277, delivery: "Why was the cookie sad at school?", punchline: "Because it felt crumby." },
  { id: 278, delivery: "What did the blanket say to the bed?", punchline: "I’ve got you covered." },
  { id: 279, delivery: "Why did the dad bring a car door to the desert?", punchline: "In case he wanted to roll down the window." },
  { id: 280, delivery: "Why did the tomato turn red again?", punchline: "It saw the salad undressing — again." },
  { id: 281, delivery: "Why did the dad stop telling time jokes?", punchline: "They were getting secondhand laughs." },
  { id: 282, delivery: "Why did the snail paint an “S” on its car?", punchline: "So people would say “Look at that S-car go!”" },
  { id: 283, delivery: "Why did the donut visit the dentist?", punchline: "To get a filling." },
  { id: 284, delivery: "Why do cows wear bells?", punchline: "Because their horns don’t work." },
  { id: 285, delivery: "What’s a dad’s favorite kind of shoes?", punchline: "Loafers." },
  { id: 286, delivery: "Why did the dad bring a map to dinner?", punchline: "He didn’t want to get lost in the sauce." },
  { id: 287, delivery: "Why did the baker get arrested?", punchline: "He was caught loafing around." },
  { id: 288, delivery: "Why was the musician arrested?", punchline: "He got in treble." },
  { id: 289, delivery: "Why did the dad wear a suit to bed?", punchline: "He wanted to sleep in style." },
  { id: 290, delivery: "Why did the snowman call his dog Frost?", punchline: "Because Frost bites." },
  { id: 291, delivery: "Why did the dad refuse to eat the clock?", punchline: "It was too time-consuming." },
  { id: 292, delivery: "Why did the duck sit on the fence?", punchline: "It was undecided." },
  { id: 293, delivery: "Why was the belt on vacation?", punchline: "It needed to buckle down." },
  { id: 294, delivery: "Why did the dad bring a notebook to bed?", punchline: "To jot down his dreams." },
  { id: 295, delivery: "Why did the calendar get promoted?", punchline: "It had a lot of dates." },
  { id: 296, delivery: "Why did the bee get married?", punchline: "Because he found his honey." },
  { id: 297, delivery: "Why was the baseball team always cold?", punchline: "Because they were full of fans." },
  { id: 298, delivery: "Why did the clock get kicked out of class?", punchline: "It tocked too much." },
  { id: 299, delivery: "Why did the dad sit on the newspaper?", punchline: "He wanted to stay current." },
  { id: 300, delivery: "Why did the banana get promoted?", punchline: "It showed great a-peel." }
]
