export interface Joke {
  id: number
  delivery: string
  punchline: string
}

export const JOKES: Joke[] = [
  { id: 1, delivery: "What do you call a factory that makes okay products?", punchline: "A satisfactory." },
  { id: 2, delivery: "I told my wife she should embrace her mistakes.", punchline: "She gave me a hug." },
  { id: 3, delivery: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field." },
  { id: 4, delivery: "Why can't you hear a pterodactyl go to the bathroom?", punchline: "Because the \"P\" is silent." },
  { id: 5, delivery: "What's orange and sounds like a parrot?", punchline: "A carrot." },
  { id: 6, delivery: "I used to play piano by ear.", punchline: "Now I use my hands." },
  { id: 7, delivery: "Why did the coffee file a police report?", punchline: "It got mugged." },
  { id: 8, delivery: "Why don't eggs tell jokes?", punchline: "They'd crack each other up." },
  { id: 9, delivery: "I only know 25 letters of the alphabet.", punchline: "I don't know y." },
  { id: 10, delivery: "Why did the golfer bring an extra pair of pants?", punchline: "In case he got a hole in one." },
  { id: 11, delivery: "What do you call fake spaghetti?", punchline: "An impasta." },
  { id: 12, delivery: "How do you organize a space party?", punchline: "You planet." },
  { id: 13, delivery: "What did one wall say to the other wall?", punchline: "I'll meet you at the corner." },
  { id: 14, delivery: "I asked the librarian if the library had books on paranoia.", punchline: "She whispered, \"They're right behind you.\"" },
  { id: 15, delivery: "Why did the math book look sad?", punchline: "It had too many problems." },
  { id: 16, delivery: "What do you call a fish wearing a bowtie?", punchline: "So-fish-ticated." },
  { id: 17, delivery: "Why don't skeletons fight each other?", punchline: "They don't have the guts." },
  { id: 18, delivery: "I used to be addicted to soap.", punchline: "But I'm clean now." },
  { id: 19, delivery: "Why did the bicycle fall over?", punchline: "It was two-tired." },
  { id: 20, delivery: "What do you call cheese that isn't yours?", punchline: "Nacho cheese." },
  { id: 21, delivery: "Did you hear about the claustrophobic astronaut?", punchline: "He needed a little space." },
  { id: 22, delivery: "I don't trust stairs.", punchline: "They're always up to something." },
  { id: 23, delivery: "Why did the photo go to jail?", punchline: "It was framed." },
  { id: 24, delivery: "What's brown and sticky?", punchline: "A stick." },
  { id: 25, delivery: "Why did the man get hit by a bike every day?", punchline: "He was stuck in a vicious cycle." },
  { id: 26, delivery: "How do you make a tissue dance?", punchline: "Put a little boogie in it." },
  { id: 27, delivery: "Why did the cookie go to the hospital?", punchline: "Because it felt crumby." },
  { id: 28, delivery: "I used to be a baker.", punchline: "I couldn't make enough dough." },
  { id: 29, delivery: "Why can't a leopard hide?", punchline: "He's always spotted." },
  { id: 30, delivery: "What did the ocean say to the shore?", punchline: "Nothing, it just waved." },
  { id: 31, delivery: "Why do seagulls fly over the sea?", punchline: "Because if they flew over the bay, they'd be bagels." },
  { id: 32, delivery: "I'm reading a book about anti-gravity.", punchline: "It's impossible to put down." },
  { id: 33, delivery: "Why did the tomato blush?", punchline: "It saw the salad dressing." },
  { id: 34, delivery: "What do you call a belt made of watches?", punchline: "A waist of time." },
  { id: 35, delivery: "Why did the computer go to the doctor?", punchline: "It caught a virus." },
  { id: 36, delivery: "What do you call a pile of cats?", punchline: "A meowtain." },
  { id: 37, delivery: "I only tell uranium jokes.", punchline: "They're always splitting sides." },
  { id: 38, delivery: "Why did the stadium get hot?", punchline: "All the fans left." },
  { id: 39, delivery: "How do you find Will Smith in the snow?", punchline: "Look for fresh prints." },
  { id: 40, delivery: "What do you call a sleeping bull?", punchline: "A bulldozer." },
  { id: 41, delivery: "Why don't oysters donate to charity?", punchline: "Because they're shellfish." },
  { id: 42, delivery: "What do you call a dinosaur with an extensive vocabulary?", punchline: "A thesaurus." },
  { id: 43, delivery: "Why did the broom arrive late?", punchline: "It swept in." },
  { id: 44, delivery: "I asked my dog what's two minus two.", punchline: "He said nothing." },
  { id: 45, delivery: "Why are elevator jokes so classic?", punchline: "They work on many levels." },
  { id: 46, delivery: "I used to hate facial hair.", punchline: "But then it grew on me." },
  { id: 47, delivery: "What do you call a cold dog?", punchline: "A chili dog." },
  { id: 48, delivery: "Why did the man name his dogs Rolex and Timex?", punchline: "They were watch dogs." },
  { id: 49, delivery: "What do you call a bee that can't make up its mind?", punchline: "A may-bee." },
  { id: 50, delivery: "Why can't your nose be 12 inches long?", punchline: "Because then it would be a foot." },
  { id: 51, delivery: "What did the buffalo say to his son when he left for college?", punchline: "Bison." },
  { id: 52, delivery: "Why did the banana go to the doctor?", punchline: "It wasn't peeling well." },
  { id: 53, delivery: "What's Forrest Gump's email password?", punchline: "1forrest1." },
  { id: 54, delivery: "How do you make holy water?", punchline: "You boil the hell out of it." },
  { id: 55, delivery: "Why did the scarecrow get promoted?", punchline: "He was outstanding in his field—again." },
  { id: 56, delivery: "Why did the barber win the race?", punchline: "He knew a shortcut." },
  { id: 57, delivery: "Why did the belt get arrested?", punchline: "It held up a pair of pants." },
  { id: 58, delivery: "What's brown, hairy, and wears sunglasses?", punchline: "A coconut on vacation." },
  { id: 59, delivery: "Why did the candle quit his job?", punchline: "He was burned out." },
  { id: 60, delivery: "What do you call a nervous javelin thrower?", punchline: "Shakespeare." },
  { id: 61, delivery: "What do you call a boomerang that doesn't come back?", punchline: "A stick." },
  { id: 62, delivery: "Why did the grape stop in the road?", punchline: "It ran out of juice." },
  { id: 63, delivery: "Why are ghosts bad at lying?", punchline: "You can see right through them." },
  { id: 64, delivery: "What do you call an alligator in a vest?", punchline: "An investigator." },
  { id: 65, delivery: "I told my doctor I broke my arm in two places.", punchline: "He told me to stop going to those places." },
  { id: 66, delivery: "Why don't crabs give to charity?", punchline: "They're a little shellfish, too." },
  { id: 67, delivery: "Why did the cyclist keep yawning?", punchline: "He was two-tired—again." },
  { id: 68, delivery: "Why did the cow become an astronaut?", punchline: "To see the moooon." },
  { id: 69, delivery: "Why did the fisherman get kicked out of class?", punchline: "He was net-working." },
  { id: 70, delivery: "What do you call a line of men waiting for a haircut?", punchline: "A barberqueue." },
  { id: 71, delivery: "Why did the smartphone wear glasses?", punchline: "It lost its contacts." },
  { id: 72, delivery: "What's the best way to watch a fly fishing tournament?", punchline: "Live stream." },
  { id: 73, delivery: "Why don't some couples go to the gym?", punchline: "Because some relationships don't work out." },
  { id: 74, delivery: "Why did the scarecrow get a raise?", punchline: "His field performance was outstanding." },
  { id: 75, delivery: "What do you call an apology written in dots and dashes?", punchline: "Remorse code." },
  { id: 76, delivery: "Why did the picture go to prison?", punchline: "It was framed—still guilty." },
  { id: 77, delivery: "Why did the chef get locked out?", punchline: "He lost his thyme." },
  { id: 78, delivery: "I used to be a gymnast.", punchline: "It didn't work out—too many somersaults." },
  { id: 79, delivery: "What do you call a very small valentine?", punchline: "A valen-tiny." },
  { id: 80, delivery: "Why did the musician get kicked out of the bakery?", punchline: "He kept trying to steal the notes." },
  { id: 81, delivery: "Why did the gardener plant a light bulb?", punchline: "He wanted to grow a power plant." },
  { id: 82, delivery: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman." },
  { id: 83, delivery: "How do you catch a whole school of fish?", punchline: "With bookworms." },
  { id: 84, delivery: "Why did the cat sit on the computer?", punchline: "It wanted to keep an eye on the mouse." },
  { id: 85, delivery: "What do you call a camel with no humps?", punchline: "Humphrey." },
  { id: 86, delivery: "Why did the man bring a spoon to the fight?", punchline: "He wanted to stir things up." },
  { id: 87, delivery: "Why did the hipster burn his tongue?", punchline: "He drank his coffee before it was cool." },
  { id: 88, delivery: "What do you call a sheep with no legs?", punchline: "A cloud." },
  { id: 89, delivery: "Why did the banker switch careers?", punchline: "He lost interest." },
  { id: 90, delivery: "Why did the clock get in trouble at school?", punchline: "It tocked back to the teacher." },
  { id: 91, delivery: "What do you call a fish with no eyes?", punchline: "Fsh." },
  { id: 92, delivery: "Why was the broom so tired?", punchline: "It had a sweeping schedule." },
  { id: 93, delivery: "What did the zero say to the eight?", punchline: "Nice belt." },
  { id: 94, delivery: "Why did the turtle cross the road?", punchline: "To get to the shell station." },
  { id: 95, delivery: "Why did the music teacher need a ladder?", punchline: "To reach the high notes." },
  { id: 96, delivery: "Why did the vampire read the newspaper?", punchline: "He heard it had great circulation." },
  { id: 97, delivery: "What do you call a can opener that doesn't work?", punchline: "A can't opener." },
  { id: 98, delivery: "Why did the lettuce win the race?", punchline: "Because it was a-head." },
  { id: 99, delivery: "How do you comfort a grammar teacher?", punchline: "There, their, they're." },
  { id: 100, delivery: "I told my kids we're having tacos for dinner.", punchline: "They said, \"That's nacho decision.\" I said, \"Yes it is.\"" }
]
