export interface Joke {
  id: number
  delivery: string
  punchline: string
}

export const JOKES: Joke[] = [
  { id: 1, delivery: "What do you call a factory that makes okay products?", punchline: "A satisfactory." },
  { id: 2, delivery: "I told my wife she should embrace her mistakes.", punchline: "She gave me a hug." },
  { id: 3, delivery: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field." },
  { id: 4, delivery: "Why can’t you hear a pterodactyl go to the bathroom?", punchline: "Because the “P” is silent." },
  { id: 5, delivery: "What’s orange and sounds like a parrot?", punchline: "A carrot." },
  { id: 6, delivery: "I used to play piano by ear.", punchline: "Now I use my hands." },
  { id: 7, delivery: "Why did the coffee file a police report?", punchline: "It got mugged." },
  { id: 8, delivery: "Why don’t eggs tell jokes?", punchline: "They’d crack each other up." },
  { id: 9, delivery: "I only know 25 letters of the alphabet.", punchline: "I don’t know y." },
  { id: 10, delivery: "Why did the golfer bring an extra pair of pants?", punchline: "In case he got a hole in one." },
  { id: 11, delivery: "What do you call fake spaghetti?", punchline: "An impasta." },
  { id: 12, delivery: "How do you organize a space party?", punchline: "You planet." },
  { id: 13, delivery: "What did one wall say to the other wall?", punchline: "I’ll meet you at the corner." },
  { id: 14, delivery: "I asked the librarian if the library had books on paranoia.", punchline: "She whispered, “They’re right behind you.”" },
  { id: 15, delivery: "Why did the math book look sad?", punchline: "It had too many problems." },
  { id: 16, delivery: "What do you call a fish wearing a bowtie?", punchline: "So-fish-ticated." },
  { id: 17, delivery: "Why don’t skeletons fight each other?", punchline: "They don’t have the guts." },
  { id: 18, delivery: "I used to be addicted to soap.", punchline: "But I’m clean now." },
  { id: 19, delivery: "Why did the bicycle fall over?", punchline: "It was two-tired." },
  { id: 20, delivery: "What do you call cheese that isn’t yours?", punchline: "Nacho cheese." },
  { id: 21, delivery: "Did you hear about the claustrophobic astronaut?", punchline: "He needed a little space." },
  { id: 22, delivery: "I don’t trust stairs.", punchline: "They’re always up to something." },
  { id: 23, delivery: "Why did the photo go to jail?", punchline: "It was framed." },
  { id: 24, delivery: "What’s brown and sticky?", punchline: "A stick." },
  { id: 25, delivery: "Why did the man get hit by a bike every day?", punchline: "He was stuck in a vicious cycle." },
  { id: 26, delivery: "How do you make a tissue dance?", punchline: "Put a little boogie in it." },
  { id: 27, delivery: "Why did the cookie go to the hospital?", punchline: "Because it felt crumby." },
  { id: 28, delivery: "I used to be a baker.", punchline: "I couldn’t make enough dough." },
  { id: 29, delivery: "Why can’t a leopard hide?", punchline: "He’s always spotted." },
  { id: 30, delivery: "What did the ocean say to the shore?", punchline: "Nothing, it just waved." },
  { id: 31, delivery: "Why do seagulls fly over the sea?", punchline: "Because if they flew over the bay, they’d be bagels." },
  { id: 32, delivery: "I’m reading a book about anti-gravity.", punchline: "It’s impossible to put down." },
  { id: 33, delivery: "Why did the tomato blush?", punchline: "It saw the salad dressing." },
  { id: 34, delivery: "What do you call a belt made of watches?", punchline: "A waist of time." },
  { id: 35, delivery: "Why did the computer go to the doctor?", punchline: "It caught a virus." },
  { id: 36, delivery: "What do you call a pile of cats?", punchline: "A meowtain." },
  { id: 37, delivery: "I only tell uranium jokes.", punchline: "They’re always splitting sides." },
  { id: 38, delivery: "Why did the stadium get hot?", punchline: "All the fans left." },
  { id: 39, delivery: "How do you find Will Smith in the snow?", punchline: "Look for fresh prints." },
  { id: 40, delivery: "What do you call a sleeping bull?", punchline: "A bulldozer." },
  { id: 41, delivery: "Why don’t oysters donate to charity?", punchline: "Because they’re shellfish." },
  { id: 42, delivery: "What do you call a dinosaur with an extensive vocabulary?", punchline: "A thesaurus." },
  { id: 43, delivery: "Why did the broom arrive late?", punchline: "It swept in." },
  { id: 44, delivery: "I asked my dog what’s two minus two.", punchline: "He said nothing." },
  { id: 45, delivery: "Why are elevator jokes so classic?", punchline: "They work on many levels." },
  { id: 46, delivery: "I used to hate facial hair.", punchline: "But then it grew on me." },
  { id: 47, delivery: "What do you call a cold dog?", punchline: "A chili dog." },
  { id: 48, delivery: "Why did the man name his dogs Rolex and Timex?", punchline: "They were watch dogs." },
  { id: 49, delivery: "What do you call a bee that can’t make up its mind?", punchline: "A may-bee." },
  { id: 50, delivery: "Why can’t your nose be 12 inches long?", punchline: "Because then it would be a foot." },
  { id: 51, delivery: "What did the buffalo say to his son when he left for college?", punchline: "Bison." },
  { id: 52, delivery: "Why did the banana go to the doctor?", punchline: "It wasn’t peeling well." },
  { id: 53, delivery: "What’s Forrest Gump’s email password?", punchline: "1forrest1." },
  { id: 54, delivery: "How do you make holy water?", punchline: "You boil the hell out of it." },
  { id: 55, delivery: "Why did the scarecrow get promoted?", punchline: "He was outstanding in his field—again." },
  { id: 56, delivery: "Why did the barber win the race?", punchline: "He knew a shortcut." },
  { id: 57, delivery: "Why did the belt get arrested?", punchline: "It held up a pair of pants." },
  { id: 58, delivery: "What’s brown, hairy, and wears sunglasses?", punchline: "A coconut on vacation." },
  { id: 59, delivery: "Why did the candle quit his job?", punchline: "He was burned out." },
  { id: 60, delivery: "What do you call a nervous javelin thrower?", punchline: "Shakespeare." },
  { id: 61, delivery: "What do you call a boomerang that doesn’t come back?", punchline: "A stick." },
  { id: 62, delivery: "Why did the grape stop in the road?", punchline: "It ran out of juice." },
  { id: 63, delivery: "Why are ghosts bad at lying?", punchline: "You can see right through them." },
  { id: 64, delivery: "What do you call an alligator in a vest?", punchline: "An investigator." },
  { id: 65, delivery: "I told my doctor I broke my arm in two places.", punchline: "He told me to stop going to those places." },
  { id: 66, delivery: "Why don’t crabs give to charity?", punchline: "They’re a little shellfish, too." },
  { id: 67, delivery: "Why did the cyclist keep yawning?", punchline: "He was two-tired—again." },
  { id: 68, delivery: "Why did the cow become an astronaut?", punchline: "To see the moooon." },
  { id: 69, delivery: "Why did the fisherman get kicked out of class?", punchline: "He was net-working." },
  { id: 70, delivery: "What do you call a line of men waiting for a haircut?", punchline: "A barberqueue." },
  { id: 71, delivery: "Why did the smartphone wear glasses?", punchline: "It lost its contacts." },
  { id: 72, delivery: "What’s the best way to watch a fly fishing tournament?", punchline: "Live stream." },
  { id: 73, delivery: "Why don’t some couples go to the gym?", punchline: "Because some relationships don’t work out." },
  { id: 74, delivery: "Why did the scarecrow get a raise?", punchline: "His field performance was outstanding." },
  { id: 75, delivery: "What do you call an apology written in dots and dashes?", punchline: "Remorse code." },
  { id: 76, delivery: "Why did the picture go to prison?", punchline: "It was framed—still guilty." },
  { id: 77, delivery: "Why did the chef get locked out?", punchline: "He lost his thyme." },
  { id: 78, delivery: "I used to be a gymnast.", punchline: "It didn’t work out—too many somersaults." },
  { id: 79, delivery: "What do you call a very small valentine?", punchline: "A valen-tiny." },
  { id: 80, delivery: "Why did the musician get kicked out of the bakery?", punchline: "He kept trying to steal the notes." },
  { id: 81, delivery: "Why did the gardener plant a light bulb?", punchline: "He wanted to grow a power plant." },
  { id: 82, delivery: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman." },
  { id: 83, delivery: "How do you catch a whole school of fish?", punchline: "With bookworms." },
  { id: 84, delivery: "Why did the cat sit on the computer?", punchline: "It wanted to keep an eye on the mouse." },
  { id: 85, delivery: "What do you call a camel with no humps?", punchline: "Humphrey." },
  { id: 86, delivery: "Why did the man bring a spoon to the fight?", punchline: "He wanted to stir things up." },
  { id: 87, delivery: "Why did the hipster burn his tongue?", punchline: "He drank his coffee before it was cool." },
  { id: 88, delivery: "What do you call a sheep with no legs?", punchline: "A cloud." },
  { id: 89, delivery: "Why did the banker switch careers?", punchline: "He lost interest." },
  { id: 90, delivery: "Why did the clock get in trouble at school?", punchline: "It tocked back to the teacher." },
  { id: 91, delivery: "What do you call a fish with no eyes?", punchline: "Fsh." },
  { id: 92, delivery: "Why was the broom so tired?", punchline: "It had a sweeping schedule." },
  { id: 93, delivery: "What did the zero say to the eight?", punchline: "Nice belt." },
  { id: 94, delivery: "Why did the turtle cross the road?", punchline: "To get to the shell station." },
  { id: 95, delivery: "Why did the music teacher need a ladder?", punchline: "To reach the high notes." },
  { id: 96, delivery: "Why did the vampire read the newspaper?", punchline: "He heard it had great circulation." },
  { id: 97, delivery: "What do you call a can opener that doesn’t work?", punchline: "A can’t opener." },
  { id: 98, delivery: "Why did the lettuce win the race?", punchline: "Because it was a-head." },
  { id: 99, delivery: "How do you comfort a grammar teacher?", punchline: "There, their, they’re." },
  { id: 100, delivery: "I told my kids we’re having tacos for dinner.", punchline: "They said, “That’s nacho decision.” I said, “Yes it is.”" },
  { id: 101, delivery: "Why did the developer go broke?", punchline: "Because he used up all his cache." },
  { id: 102, delivery: "Why did the PowerPoint presentation cross the road?", punchline: "To get to the next slide." },
  { id: 103, delivery: "What do you call a dad who makes memes?", punchline: "A pun-fluencer." },
  { id: 104, delivery: "Why was the computer cold?", punchline: "It left its Windows open." },
  { id: 105, delivery: "What do you call a lazy kangaroo?", punchline: "A pouch potato." },
  { id: 106, delivery: "Why did the AI go to therapy?", punchline: "It had deep learning issues." },
  { id: 107, delivery: "Why don’t programmers like nature?", punchline: "Too many bugs." },
  { id: 108, delivery: "What’s a pirate’s least favorite letter?", punchline: "Dear Sir or Madam…" },
  { id: 109, delivery: "Why did the chicken join a band?", punchline: "Because it already had drumsticks." },
  { id: 110, delivery: "How do robots pay for things?", punchline: "With cache or crypto." },
  { id: 111, delivery: "Why did the office printer file a complaint?", punchline: "It was tired of being jammed." },
  { id: 112, delivery: "What do you call a dad who tells jokes about pizza?", punchline: "A pun-za lover." },
  { id: 113, delivery: "Why did the spreadsheet go to therapy?", punchline: "It had too many cells." },
  { id: 114, delivery: "Why don’t you ever play hide and seek with mountains?", punchline: "They always peak." },
  { id: 115, delivery: "How does the internet sneeze?", punchline: "Ah-choo-tube!" },
  { id: 116, delivery: "Why was the smartphone acting so smart?", punchline: "It finally got an upgrade." },
  { id: 117, delivery: "Why did the boss bring a pencil to the meeting?", punchline: "To draw conclusions." },
  { id: 118, delivery: "Why was the broom late to work?", punchline: "It overswept." },
  { id: 119, delivery: "What do you call a group of disorganized cats?", punchline: "A cat-astrophe." },
  { id: 120, delivery: "Why did the Wi-Fi break up with the router?", punchline: "The connection was lost." },
  { id: 121, delivery: "How do cows stay up to date?", punchline: "They read the moos-paper." },
  { id: 122, delivery: "Why did the gamer get kicked out of the bar?", punchline: "He was pressing “escape.”" },
  { id: 123, delivery: "Why did the dad put his money in the blender?", punchline: "He wanted liquid assets." },
  { id: 124, delivery: "How does the moon cut his hair?", punchline: "Eclipse it." },
  { id: 125, delivery: "Why did the employee bring a ladder to work?", punchline: "The boss said promotions were up." },
  { id: 126, delivery: "Why did the clock get sent home early?", punchline: "It needed some downtime." },
  { id: 127, delivery: "What’s a cat’s favorite social media platform?", punchline: "Insta-purr-gram." },
  { id: 128, delivery: "Why did the dad start a podcast?", punchline: "He wanted to share his sound advice." },
  { id: 129, delivery: "Why did the email break up with the inbox?", punchline: "Too much spam in the relationship." },
  { id: 130, delivery: "Why do vampires use mouthwash?", punchline: "Because they have bat breath." },
  { id: 131, delivery: "What do you call a bear with no teeth?", punchline: "A gummy bear." },
  { id: 132, delivery: "Why did the employee sit on the clock?", punchline: "He wanted to be on time." },
  { id: 133, delivery: "Why did the dad bring string to the bar?", punchline: "He wanted to tie one on." },
  { id: 134, delivery: "Why was the selfie so confident?", punchline: "It had the best angle on life." },
  { id: 135, delivery: "What did one keyboard say to the other?", punchline: "You’re my type." },
  { id: 136, delivery: "Why did the calendar look depressed?", punchline: "Its days were numbered." },
  { id: 137, delivery: "Why did the coffee shop close early?", punchline: "A latte problems." },
  { id: 138, delivery: "Why did the dad stare at the orange juice carton?", punchline: "It said, “concentrate.”" },
  { id: 139, delivery: "What do you call someone who takes care of chickens?", punchline: "A chicken tender." },
  { id: 140, delivery: "Why do astronauts use social media?", punchline: "To get more space followers." },
  { id: 141, delivery: "Why did the dad join a coding bootcamp?", punchline: "He heard it was a class act." },
  { id: 142, delivery: "How does a penguin build its house?", punchline: "Igloos it together." },
  { id: 143, delivery: "What’s a skeleton’s favorite snack?", punchline: "Spare ribs." },
  { id: 144, delivery: "Why did the tomato turn red?", punchline: "It saw the ketchup bottle." },
  { id: 145, delivery: "Why did the spreadsheet cross the road?", punchline: "To get to the other column." },
  { id: 146, delivery: "How do you tell if a dad joke is a dad joke?", punchline: "It becomes apparent." },
  { id: 147, delivery: "Why did the gamer sit so close to the TV?", punchline: "He wanted to play it by ear." },
  { id: 148, delivery: "What do you call a singing laptop?", punchline: "A Dell." },
  { id: 149, delivery: "Why did the password go to jail?", punchline: "It was too weak." },
  { id: 150, delivery: "What’s a dad’s favorite instrument?", punchline: "The dad-bodhran." },
  { id: 151, delivery: "Why was the broom promoted?", punchline: "It swept the competition." },
  { id: 152, delivery: "What’s the best way to make holy water?", punchline: "You boil the hell out of it." },
  { id: 153, delivery: "Why did the dad bring a battery to dinner?", punchline: "He wanted a charged atmosphere." },
  { id: 154, delivery: "Why do bees have sticky hair?", punchline: "They use honeycombs." },
  { id: 155, delivery: "Why did the laptop marry the mouse?", punchline: "They clicked." },
  { id: 156, delivery: "What do you call a fake noodle?", punchline: "An impasta—still funny the second time." },
  { id: 157, delivery: "Why did the dad refuse to play cards in the jungle?", punchline: "Too many cheetahs." },
  { id: 158, delivery: "Why did the skeleton start a band?", punchline: "He had the bones for it." },
  { id: 159, delivery: "Why did the office worker sit on a stapler?", punchline: "To stay connected." },
  { id: 160, delivery: "What do you call an apology from a robot?", punchline: "Error in judgment." },
  { id: 161, delivery: "Why did the tech support guy quit?", punchline: "He lost his drive." },
  { id: 162, delivery: "Why did the fortune cookie go to therapy?", punchline: "It couldn’t handle being broken inside." },
  { id: 163, delivery: "What did one volcano say to the other?", punchline: "I lava you." },
  { id: 164, delivery: "Why did the math teacher love parks?", punchline: "All the natural logs." },
  { id: 165, delivery: "Why did the dad sit next to the Wi-Fi router?", punchline: "He wanted a better connection with his kids." },
  { id: 166, delivery: "Why did the penguin drive so fast?", punchline: "He was trying to break the ice." },
  { id: 167, delivery: "Why do fathers take extra socks to the golf course?", punchline: "In case they get a hole in one." },
  { id: 168, delivery: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies!" },
  { id: 169, delivery: "What’s a dad’s favorite time?", punchline: "6:30 — hands down." },
  { id: 170, delivery: "Why did the gamer sleep under his desk?", punchline: "He wanted to save his progress." },
  { id: 171, delivery: "Why was the database so calm?", punchline: "It had ACID properties." },
  { id: 172, delivery: "Why did the dad start a gardening blog?", punchline: "He wanted to turnip the engagement." },
  { id: 173, delivery: "What do you call a boomerang that won’t come back?", punchline: "A stick — still classic." },
  { id: 174, delivery: "Why did the employee stare at his orange juice?", punchline: "Because it said “concentrate.” (Dad jokes recycle.)" },
  { id: 175, delivery: "Why did the meme go to school?", punchline: "To become a little more relatable." },
  { id: 176, delivery: "Why did the dad refuse to get new shoes?", punchline: "His sole was still good." },
  { id: 177, delivery: "Why do programmers prefer dark mode?", punchline: "Because light attracts bugs." },
  { id: 178, delivery: "Why did the dad sit in the corner at the restaurant?", punchline: "He wanted to have a side order." },
  { id: 179, delivery: "Why was the broom the best employee?", punchline: "It always swept up after itself." },
  { id: 180, delivery: "What do you call a broken can opener?", punchline: "A can’t opener." },
  { id: 181, delivery: "Why did the dad take a ladder to the bar?", punchline: "He heard the drinks were on the house." },
  { id: 182, delivery: "Why did the baker stop making donuts?", punchline: "He got tired of the hole business." },
  { id: 183, delivery: "Why did the dad take his clock to the vet?", punchline: "It had ticks." },
  { id: 184, delivery: "Why did the website go to the doctor?", punchline: "It had a bad case of cookies." },
  { id: 185, delivery: "Why do dads love elevators?", punchline: "Because they’re uplifting." },
  { id: 186, delivery: "Why did the dad get kicked out of the music store?", punchline: "He couldn’t Handel it." },
  { id: 187, delivery: "Why did the cloud get invited to parties?", punchline: "Because it was the life of the server." },
  { id: 188, delivery: "What do you call a fish that tells jokes?", punchline: "A clownfish." },
  { id: 189, delivery: "Why did the dad take a nap on the keyboard?", punchline: "He needed a bit of rest control." },
  { id: 190, delivery: "Why did the phone go to art school?", punchline: "It wanted to improve its selfies." },
  { id: 191, delivery: "Why was the gardener so good at math?", punchline: "He knew how to multiply." },
  { id: 192, delivery: "Why did the dad throw his alarm clock out the window?", punchline: "He wanted to see time fly." },
  { id: 193, delivery: "What do you call an iPhone that isn’t kidding around?", punchline: "Dead Siri-ous." },
  { id: 194, delivery: "What did the left eye say to the right eye?", punchline: "Between you and me, something smells." },
  { id: 195, delivery: "Why did the dad install a skylight?", punchline: "To let a little light-heartedness in." },
  { id: 196, delivery: "What do you call a cow that plays the guitar?", punchline: "A moo-sician." },
  { id: 197, delivery: "Why did the employee bring toilet paper to the meeting?", punchline: "It was a crapshoot." },
  { id: 198, delivery: "Why did the dad buy new socks?", punchline: "He wanted to step up his game." },
  { id: 199, delivery: "Why did the dog sit in the shade?", punchline: "Because it didn’t want to be a hot dog." },
  { id: 200, delivery: "What do you call a group of dads telling jokes?", punchline: "A pun-demic." },
  { id: 201, delivery: "Why did the developer stay home from work?", punchline: "He didn’t feel up to code." },
  { id: 202, delivery: "Why did the cloud get nervous at the presentation?", punchline: "Too much pressure in the atmosphere." },
  { id: 203, delivery: "What do you call a sleeping computer?", punchline: "A power nap-top." },
  { id: 204, delivery: "Why did the gamer bring a broom to the tournament?", punchline: "To sweep the competition." },
  { id: 205, delivery: "What’s a dad’s favorite kind of music?", punchline: "Pop." },
  { id: 206, delivery: "Why did the stapler break up with the paper?", punchline: "It found someone more binding." },
  { id: 207, delivery: "How do you make a computer laugh?", punchline: "Tell it a byte-sized joke." },
  { id: 208, delivery: "Why did the dad put his car in the oven?", punchline: "He wanted a hot rod." },
  { id: 209, delivery: "Why did the tech startup hire a magician?", punchline: "To make their funding disappear." },
  { id: 210, delivery: "Why was the computer so good at singing?", punchline: "It had perfect pitch." },
  { id: 211, delivery: "Why did the dad bring his watch to the bar?", punchline: "He wanted to have a good time." },
  { id: 212, delivery: "What’s a hacker’s favorite kind of tea?", punchline: "URL grey." },
  { id: 213, delivery: "Why did the dad start whispering around his Wi-Fi?", punchline: "He didn’t want to make a scene." },
  { id: 214, delivery: "Why did the robot go on a diet?", punchline: "Too many bytes." },
  { id: 215, delivery: "Why did the dad refuse to play poker with the jungle animals?", punchline: "He was afraid of cheetahs." },
  { id: 216, delivery: "How does a cat end a fight?", punchline: "With a hiss-truce." },
  { id: 217, delivery: "Why was the broom a terrible roommate?", punchline: "It swept under the rug." },
  { id: 218, delivery: "Why do dads always win hide and seek?", punchline: "Because good dads are outstanding in their field." },
  { id: 219, delivery: "Why did the bicycle stand on its own?", punchline: "It was two-tired of falling over." },
  { id: 220, delivery: "Why did the computer take a nap?", punchline: "It needed to reboot." },
  { id: 221, delivery: "Why don’t we see elephants hiding in trees?", punchline: "Because they’re so good at it." },
  { id: 222, delivery: "Why was the photo always so calm?", punchline: "It was well composed." },
  { id: 223, delivery: "How do you fix a broken pizza?", punchline: "With tomato paste." },
  { id: 224, delivery: "Why do bees hum?", punchline: "Because they don’t know the words." },
  { id: 225, delivery: "Why was the dad staring at the can of orange juice?", punchline: "Because it said “concentrate” — again." },
  { id: 226, delivery: "Why did the dad’s joke go to therapy?", punchline: "It couldn’t find its punchline." },
  { id: 227, delivery: "What’s a dad’s favorite kind of exercise?", punchline: "Diddly-squats." },
  { id: 228, delivery: "Why did the scarecrow become a successful influencer?", punchline: "He was outstanding in his field — and had great reach." },
  { id: 229, delivery: "What do you call a sleeping dinosaur?", punchline: "A dino-snore." },
  { id: 230, delivery: "Why was the Wi-Fi acting up?", punchline: "It needed a router reboot-ation." },
  { id: 231, delivery: "How do cows send secret messages?", punchline: "Steganomo-graphy." },
  { id: 232, delivery: "What do you call a dad who tells jokes while grilling?", punchline: "A pun-flame thrower." },
  { id: 233, delivery: "Why did the dad bring an umbrella to the barbecue?", punchline: "For the drizzle." },
  { id: 234, delivery: "Why did the gamer’s chair break?", punchline: "Too much sitting XP." },
  { id: 235, delivery: "Why did the refrigerator win employee of the month?", punchline: "It kept its cool." },
  { id: 236, delivery: "Why did the office computer sing?", punchline: "It had too many tabs open and needed to vent." },
  { id: 237, delivery: "Why did the dad take up fishing?", punchline: "He found it reel-axing." },
  { id: 238, delivery: "Why do ducks have feathers?", punchline: "To cover their butt-quacks." },
  { id: 239, delivery: "What did the janitor say when he jumped out of the closet?", punchline: "Supplies! (Yes, it’s still funny.)" },
  { id: 240, delivery: "Why did the robot break up with its girlfriend?", punchline: "She had too many parameters." },
  { id: 241, delivery: "Why did the dad put his keys in the fridge?", punchline: "He wanted a cool start to his day." },
  { id: 242, delivery: "Why did the pancake apply for a job?", punchline: "It wanted to flip its career." },
  { id: 243, delivery: "Why did the sandwich go to the gym?", punchline: "To get shredded." },
  { id: 244, delivery: "How do trees access the internet?", punchline: "They log in." },
  { id: 245, delivery: "What do you call a belt made of money?", punchline: "A waist of cash." },
  { id: 246, delivery: "Why did the dad sit on the remote?", punchline: "He wanted to control himself." },
  { id: 247, delivery: "Why was the cloud so confident?", punchline: "It had plenty of self-storage." },
  { id: 248, delivery: "Why did the math teacher open a bakery?", punchline: "She was great with pie charts." },
  { id: 249, delivery: "Why did the skeleton go to the party alone?", punchline: "He had no body to go with." },
  { id: 250, delivery: "Why did the smartphone go to the dentist?", punchline: "It had Bluetooth." },
  { id: 251, delivery: "Why do dads make terrible secret agents?", punchline: "They always crack under pun-pressure." },
  { id: 252, delivery: "Why did the car apply for a job?", punchline: "It wanted to get a drive in life." },
  { id: 253, delivery: "Why do frogs never get stressed?", punchline: "They eat what bugs them." },
  { id: 254, delivery: "Why did the programmer always stay calm?", punchline: "He had exception handling." },
  { id: 255, delivery: "Why did the chef quit his job?", punchline: "He couldn’t make enough dough." },
  { id: 256, delivery: "What’s a skeleton’s least favorite room?", punchline: "The living room." },
  { id: 257, delivery: "Why did the dad bring a ruler to bed?", punchline: "To see how long he slept." },
  { id: 258, delivery: "Why was the baby strawberry crying?", punchline: "Its parents were in a jam." },
  { id: 259, delivery: "What’s a cat’s favorite color?", punchline: "Purr-ple." },
  { id: 260, delivery: "Why did the light bulb break up with the switch?", punchline: "There was no spark." },
  { id: 261, delivery: "What’s a computer’s favorite snack?", punchline: "Microchips." },
  { id: 262, delivery: "Why did the gardener quit?", punchline: "His celery wasn’t high enough." },
  { id: 263, delivery: "Why did the banana go to therapy?", punchline: "It couldn’t peel with life." },
  { id: 264, delivery: "What did the fish say when it hit the wall?", punchline: "Dam." },
  { id: 265, delivery: "Why was the cookie so sad?", punchline: "Because its mom was a wafer too long." },
  { id: 266, delivery: "Why was the dad’s belt arrested?", punchline: "For holding up a pair of pants — again." },
  { id: 267, delivery: "Why was the broom late?", punchline: "It overswept — classic." },
  { id: 268, delivery: "What do you call a sheep that does karate?", punchline: "Lamb chop." },
  { id: 269, delivery: "Why did the snowman look in the bag of carrots?", punchline: "He was picking his nose." },
  { id: 270, delivery: "What do you call a factory that makes OK products?", punchline: "A satisfactory — still checks out." },
  { id: 271, delivery: "Why did the dad join the choir?", punchline: "He wanted to raise the baritone." },
  { id: 272, delivery: "Why do ducks make great detectives?", punchline: "They always quack the case." },
  { id: 273, delivery: "Why did the bicycle need therapy?", punchline: "It was tired of being walked all over." },
  { id: 274, delivery: "What do you call an indecisive bee?", punchline: "A may-bee." },
  { id: 275, delivery: "Why did the dad stare at his can of soda?", punchline: "Because it was pop art." },
  { id: 276, delivery: "Why did the scarecrow become a DJ?", punchline: "He was outstanding in his field — and had sick beats." },
  { id: 277, delivery: "Why was the cookie sad at school?", punchline: "Because it felt crumby." },
  { id: 278, delivery: "What did the blanket say to the bed?", punchline: "I’ve got you covered." },
  { id: 279, delivery: "Why did the dad bring a car door to the desert?", punchline: "In case he wanted to roll down the window." },
  { id: 280, delivery: "Why did the tomato turn red again?", punchline: "It saw the salad undressing — again." },
  { id: 281, delivery: "Why did the dad stop telling time jokes?", punchline: "They were getting secondhand laughs." },
  { id: 282, delivery: "Why did the snail paint an “S” on its car?", punchline: "So people would say “Look at that S-car go!”" },
  { id: 283, delivery: "Why did the donut visit the dentist?", punchline: "To get a filling." },
  { id: 284, delivery: "Why do cows wear bells?", punchline: "Because their horns don’t work." },
  { id: 285, delivery: "What’s a dad’s favorite kind of shoes?", punchline: "Loafers." },
  { id: 286, delivery: "Why did the dad bring a map to dinner?", punchline: "He didn’t want to get lost in the sauce." },
  { id: 287, delivery: "Why did the baker get arrested?", punchline: "He was caught loafing around." },
  { id: 288, delivery: "Why was the musician arrested?", punchline: "He got in treble." },
  { id: 289, delivery: "Why did the dad wear a suit to bed?", punchline: "He wanted to sleep in style." },
  { id: 290, delivery: "Why did the snowman call his dog Frost?", punchline: "Because Frost bites." },
  { id: 291, delivery: "Why did the dad refuse to eat the clock?", punchline: "It was too time-consuming." },
  { id: 292, delivery: "Why did the duck sit on the fence?", punchline: "It was undecided." },
  { id: 293, delivery: "Why was the belt on vacation?", punchline: "It needed to buckle down." },
  { id: 294, delivery: "Why did the dad bring a notebook to bed?", punchline: "To jot down his dreams." },
  { id: 295, delivery: "Why did the calendar get promoted?", punchline: "It had a lot of dates." },
  { id: 296, delivery: "Why did the bee get married?", punchline: "Because he found his honey." },
  { id: 297, delivery: "Why was the baseball team always cold?", punchline: "Because they were full of fans." },
  { id: 298, delivery: "Why did the clock get kicked out of class?", punchline: "It tocked too much." },
  { id: 299, delivery: "Why did the dad sit on the newspaper?", punchline: "He wanted to stay current." },
  { id: 300, delivery: "Why did the banana get promoted?", punchline: "It showed great a-peel." },
  { id: 301, delivery: "Why did the turkey join a band?", punchline: "Because it had drumsticks." },
  { id: 302, delivery: "What did the snowman say to the other snowman?", punchline: "Do you smell carrots?" },
  { id: 303, delivery: "Why did Santa go to music school?", punchline: "So he could improve his wrapping skills." },
  { id: 304, delivery: "Why did the computer keep freezing?", punchline: "It left its Windows open again." },
  { id: 305, delivery: "What’s a programmer’s favorite hangout spot?", punchline: "The Foo Bar." },
  { id: 306, delivery: "What do you call a cow on vacation?", punchline: "Moo-tivated." },
  { id: 307, delivery: "Why was the math book happy?", punchline: "It finally solved all its problems." },
  { id: 308, delivery: "Why did the turkey sit on the drum?", punchline: "To be part of the Thanksgiving band." },
  { id: 309, delivery: "How does Santa keep track of all the fireplaces?", punchline: "He logs them." },
  { id: 310, delivery: "What’s a dad’s favorite Christmas carol?", punchline: "Silent Night — after the kids go to bed." },
  { id: 311, delivery: "Why did the ornament go to therapy?", punchline: "It couldn’t handle the hang-ups." },
  { id: 312, delivery: "Why did the Wi-Fi go to church?", punchline: "It needed a stronger connection." },
  { id: 313, delivery: "What do you get if you cross a snowman and a dog?", punchline: "Frostbite." },
  { id: 314, delivery: "What did the gingerbread man use to fix his house?", punchline: "Icing and sugar glue." },
  { id: 315, delivery: "Why was the elf so good at spelling?", punchline: "He loved the elf-a-bet." },
  { id: 316, delivery: "Why did the Christmas tree go to the barber?", punchline: "It needed a trim before the big day." },
  { id: 317, delivery: "What did one snowflake say to the other?", punchline: "You’re one of a kind." },
  { id: 318, delivery: "Why did the calendar break up with the clock?", punchline: "It needed more space." },
  { id: 319, delivery: "Why did the turkey refuse dessert?", punchline: "He was already stuffed." },
  { id: 320, delivery: "What’s a snowman’s favorite breakfast?", punchline: "Frosted Flakes." },
  { id: 321, delivery: "Why did Rudolph get a bad grade in school?", punchline: "He went down in history — but didn’t study." },
  { id: 322, delivery: "Why do dads love eggnog?", punchline: "It’s the one time they can “mix spirits” without judgment." },
  { id: 323, delivery: "What do you call a dad joke told on Christmas?", punchline: "A yule laugh." },
  { id: 324, delivery: "Why did Santa go to therapy?", punchline: "He stopped believing in himself." },
  { id: 325, delivery: "What’s a snowman’s favorite game?", punchline: "Freeze tag." },
  { id: 326, delivery: "What did Adam say on December 31st?", punchline: "It’s New Year’s, Eve!" },
  { id: 327, delivery: "Why did the Hanukkah menorah go to the gym?", punchline: "To get lit." },
  { id: 328, delivery: "What do you call Santa when he takes a break?", punchline: "Santa Pause." },
  { id: 329, delivery: "What do you call a reindeer that tells jokes?", punchline: "Comet-ian." },
  { id: 330, delivery: "Why did the snowman call his dog Frost?", punchline: "Because Frost bites — still true." },
  { id: 331, delivery: "Why did the menorah win employee of the month?", punchline: "It outshone everyone else." },
  { id: 332, delivery: "Why did the ornament get promoted?", punchline: "It was outstanding in its field of tinsel." },
  { id: 333, delivery: "What do you call a broke Santa?", punchline: "Saint Nickel-less." },
  { id: 334, delivery: "Why do snowmen love weekends?", punchline: "They can chill." },
  { id: 335, delivery: "What do you call a snowman with a temper?", punchline: "A meltdown." },
  { id: 336, delivery: "Why did the office Christmas party end early?", punchline: "Someone dropped the punchline." },
  { id: 337, delivery: "Why did the present go to therapy?", punchline: "It had too much emotional baggage." },
  { id: 338, delivery: "What did Santa say to the bartender?", punchline: "I’ll take the house sleigh-special." },
  { id: 339, delivery: "Why did the dad buy a fake Christmas tree?", punchline: "He was tired of pine-ing for the real one." },
  { id: 340, delivery: "Why did Frosty go to the middle of the desert?", punchline: "To chill out — badly." },
  { id: 341, delivery: "What’s a snowman’s least favorite snack?", punchline: "Sun Chips." },
  { id: 342, delivery: "What’s Santa’s favorite state?", punchline: "Idaho-ho-ho!" },
  { id: 343, delivery: "What kind of music do elves love?", punchline: "Wrap music." },
  { id: 344, delivery: "Why did the Christmas tree go to therapy?", punchline: "It couldn’t get to the root of its problems." },
  { id: 345, delivery: "What do you call people who are afraid of Santa?", punchline: "Claustrophobic." },
  { id: 346, delivery: "Why did the snowman call a plumber?", punchline: "He had a melt down." },
  { id: 347, delivery: "Why was the dad so happy at New Year’s?", punchline: "He got to start over on his resolutions — again." },
  { id: 348, delivery: "What do you call Santa’s helpers in the tech department?", punchline: "Subordinate Clauses." },
  { id: 349, delivery: "What do you call a dad who tells holiday jokes?", punchline: "A pun-derful life." },
  { id: 350, delivery: "Why did the cookie go to the Christmas party?", punchline: "It was feeling crumby." },
  { id: 351, delivery: "Why did Santa start a podcast?", punchline: "He wanted to spread good cheer on all platforms." },
  { id: 352, delivery: "What do you call a snowman with a six-pack?", punchline: "An abdominal snowman." },
  { id: 353, delivery: "Why do reindeer love Beyoncé?", punchline: "Because she sleighs." },
  { id: 354, delivery: "What did one Christmas light say to the other?", punchline: "You light up my life." },
  { id: 355, delivery: "Why did the Christmas cookie go to therapy?", punchline: "It was crumbling under pressure." },
  { id: 356, delivery: "Why was the gingerbread man late?", punchline: "He couldn’t catch the bus — he was too sweet." },
  { id: 357, delivery: "What do you call Santa when he loses his pants?", punchline: "Saint Knickerless." },
  { id: 358, delivery: "What did the dad say when he saw the Christmas budget?", punchline: "Yikes — that’s snow joke." },
  { id: 359, delivery: "Why was the snowman so calm?", punchline: "Because he had ice in his veins." },
  { id: 360, delivery: "Why do dads love the holidays?", punchline: "Because everything comes with receipts." },
  { id: 361, delivery: "What do snowmen eat for dessert?", punchline: "Ice Krispies." },
  { id: 362, delivery: "Why did the calendar get so popular in December?", punchline: "It had a lot of dates." },
  { id: 363, delivery: "What’s Santa’s favorite type of math?", punchline: "Snow-metry." },
  { id: 364, delivery: "What do you get when you cross a Christmas tree and an iPad?", punchline: "A pine-apple." },
  { id: 365, delivery: "Why was the snowman looking through the carrots?", punchline: "He was picking his nose — again." },
  { id: 366, delivery: "Why did the reindeer wear sunglasses?", punchline: "Because it was snow bright." },
  { id: 367, delivery: "What’s a Christmas tree’s favorite candy?", punchline: "Orna-mints." },
  { id: 368, delivery: "What’s a dad’s favorite part of Christmas dinner?", punchline: "The silent night after." },
  { id: 369, delivery: "Why did the turkey bring a microphone to dinner?", punchline: "It wanted to drop a few lines." },
  { id: 370, delivery: "Why was the cranberry so stressed?", punchline: "It was in a jam." },
  { id: 371, delivery: "What’s a turkey’s favorite dessert?", punchline: "Peach gobbler." },
  { id: 372, delivery: "Why was the snowman at Thanksgiving dinner?", punchline: "He heard it was chill." },
  { id: 373, delivery: "What’s a pilgrim’s favorite kind of music?", punchline: "Plymouth Rock." },
  { id: 374, delivery: "Why was the stuffing acting strange?", punchline: "It couldn’t handle the pressure cooker." },
  { id: 375, delivery: "What’s a pumpkin pie’s least favorite subject?", punchline: "Math — it’s irrational." },
  { id: 376, delivery: "Why did the cranberry sauce blush?", punchline: "It saw the turkey dressing." },
  { id: 377, delivery: "What’s Santa’s favorite type of sandwich?", punchline: "Peanut butter and jolly." },
  { id: 378, delivery: "Why did the menorah break up with the candle?", punchline: "It couldn’t handle the wax drama." },
  { id: 379, delivery: "Why did the New Year’s resolution go to the gym?", punchline: "For a fresh start — it didn’t last long." },
  { id: 380, delivery: "What’s a snowman’s favorite meal?", punchline: "Iceburgers." },
  { id: 381, delivery: "What did one ornament say to another?", punchline: "Hang in there!" },
  { id: 382, delivery: "Why was Santa’s helper feeling depressed?", punchline: "He had low elf-esteem." },
  { id: 383, delivery: "Why did the gingerbread man go to school?", punchline: "To become a smart cookie." },
  { id: 384, delivery: "Why was the reindeer so good at jokes?", punchline: "It had the best delivery." },
  { id: 385, delivery: "Why was the dad sitting under the mistletoe?", punchline: "He misunderstood “plant-based dating.”" },
  { id: 386, delivery: "Why was the calendar nervous on December 31st?", punchline: "Its days were numbered." },
  { id: 387, delivery: "What do you call a snowman with a temper?", punchline: "An ice-hole." },
  { id: 388, delivery: "Why did the snowman go to the office?", punchline: "He wanted to work on his cool demeanor." },
  { id: 389, delivery: "What did Santa say when his sleigh broke down?", punchline: "“Looks like I’ll have to walk this Claus.”" },
  { id: 390, delivery: "Why did the elf quit social media?", punchline: "Too much compare and Claus." },
  { id: 391, delivery: "What did one New Year’s resolution say to the other?", punchline: "“You won’t last either.”" },
  { id: 392, delivery: "Why do snowmen hate traffic?", punchline: "It gives them the chills." },
  { id: 393, delivery: "Why did the snowflake refuse to fight?", punchline: "It didn’t want to be a flake-out." },
  { id: 394, delivery: "Why did Santa get a parking ticket?", punchline: "He sleighed in a no-fly zone." },
  { id: 395, delivery: "Why was the dreidel so happy?", punchline: "It was on a roll." },
  { id: 396, delivery: "What’s a menorah’s favorite workout?", punchline: "Candle-robics." },
  { id: 397, delivery: "Why was the latke embarrassed?", punchline: "It saw the sour cream undressing." },
  { id: 398, delivery: "Why did the snowman look so confident?", punchline: "He had chill energy." },
  { id: 399, delivery: "Why did Santa’s reindeer look shocked?", punchline: "It saw the Claus in his contract." },
  { id: 400, delivery: "Why did the fireworks get promoted?", punchline: "They were on fire this year." },
  { id: 401, delivery: "What’s a dad’s favorite part of Hanukkah?", punchline: "Eight nights of leftovers." },
  { id: 402, delivery: "Why did the dreidel start a podcast?", punchline: "It wanted to spin some good stories." },
  { id: 403, delivery: "Why did the dad wrap all the presents in aluminum foil?", punchline: "He wanted to make them shine." },
  { id: 404, delivery: "Why did the New Year’s countdown go to therapy?", punchline: "It was dealing with a lot of pressure." },
  { id: 405, delivery: "What’s a snowman’s least favorite activity?", punchline: "Global warming." },
  { id: 406, delivery: "What do you call an elf who sings off-key?", punchline: "A wrapper with bad flow." },
  { id: 407, delivery: "Why did Santa take up gardening?", punchline: "He wanted to work on his ho-ho-horticulture." },
  { id: 408, delivery: "Why did the gingerbread man start meditating?", punchline: "To stay centered." },
  { id: 409, delivery: "Why did the dad get a menorah tattoo?", punchline: "He wanted something permanent to light up his life." },
  { id: 410, delivery: "Why did the snowman join a dating app?", punchline: "He was looking for a flake connection." },
  { id: 411, delivery: "What’s Santa’s favorite movie?", punchline: "“Clause and Effect.”" },
  { id: 412, delivery: "Why did the turkey join the circus?", punchline: "He wanted to be a drumstick performer." },
  { id: 413, delivery: "Why did the snowman become a motivational speaker?", punchline: "He had a cool message." },
  { id: 414, delivery: "Why do dads love wrapping presents?", punchline: "It’s the one time they can actually fold under pressure." },
  { id: 415, delivery: "Why was the mistletoe so confident?", punchline: "It always got kissed." },
  { id: 416, delivery: "Why did Santa’s workshop go viral?", punchline: "Because of the elf-tok videos." },
  { id: 417, delivery: "What’s Santa’s favorite type of coffee?", punchline: "Sleigh-latte." },
  { id: 418, delivery: "Why did the dad stay up late on New Year’s Eve?", punchline: "To make sure the old year left." },
  { id: 419, delivery: "What’s a dad’s favorite Christmas movie line?", punchline: "“Yippee-ki-yule!”" },
  { id: 420, delivery: "Why did the Christmas light get promoted?", punchline: "It was brilliant." },
  { id: 421, delivery: "Why did Santa stop using social media?", punchline: "Too many trolls." },
  { id: 422, delivery: "What’s Rudolph’s favorite snack?", punchline: "Snow cones." },
  { id: 423, delivery: "Why did the dad buy so many lights?", punchline: "He wanted to make spirits bright — literally." },
  { id: 424, delivery: "What did the snowman say when it finished its dinner?", punchline: "I’m stuffed to the brim." },
  { id: 425, delivery: "Why was Santa good at karate?", punchline: "Because he had a black belt in chimney entry." },
  { id: 426, delivery: "What’s a snowman’s favorite drink?", punchline: "Ice tea." },
  { id: 427, delivery: "Why did the dad volunteer to cook Christmas dinner?", punchline: "He wanted to roast something besides the kids’ music taste." },
  { id: 428, delivery: "What do you call a snowman’s dog?", punchline: "Slush puppy." },
  { id: 429, delivery: "Why did Santa refuse to wear his glasses?", punchline: "He wanted to see what he could sleigh without them." },
  { id: 430, delivery: "Why did the elf get kicked out of school?", punchline: "Too many toy-late assignments." },
  { id: 431, delivery: "Why was the candy cane so polite?", punchline: "It was raised with sweet manners." },
  { id: 432, delivery: "What’s Santa’s favorite brand of chips?", punchline: "Kringle-cut." },
  { id: 433, delivery: "Why did the snowman refuse dessert?", punchline: "He was already chilled to the core." },
  { id: 434, delivery: "What did the clock say on New Year’s Eve?", punchline: "Time flies when you’re having rum." },
  { id: 435, delivery: "Why did the dad refuse to take down the lights?", punchline: "He said they were now “year-round ambiance.”" },
  { id: 436, delivery: "What did Santa name his cat?", punchline: "Claws." },
  { id: 437, delivery: "Why was the snowman afraid of the sun?", punchline: "He was having a meltdown." },
  { id: 438, delivery: "What’s Santa’s favorite mode of communication?", punchline: "Sleigh-mail." },
  { id: 439, delivery: "Why did the dad refuse to eat the fruitcake?", punchline: "He didn’t trust something that could survive the apocalypse." },
  { id: 440, delivery: "Why did the turkey cross the road twice?", punchline: "To prove he wasn’t chicken." },
  { id: 441, delivery: "Why did the dad put his Christmas tree in the freezer?", punchline: "He wanted to chill with the fir." },
  { id: 442, delivery: "What did one ornament say to the other?", punchline: "Stop hanging around!" },
  { id: 443, delivery: "Why was Santa’s helper so cold?", punchline: "He had a low elf-esteem problem." },
  { id: 444, delivery: "What do you call Santa when he works at a bakery?", punchline: "Krisp Kringle." },
  { id: 445, delivery: "What’s Santa’s favorite snack food?", punchline: "Jingle bell peppers." },
  { id: 446, delivery: "Why did the snowman start a band?", punchline: "He wanted to make some cool tunes." },
  { id: 447, delivery: "Why did Santa go to college?", punchline: "To improve his present-ation skills." },
  { id: 448, delivery: "Why do dads like wrapping presents last minute?", punchline: "They work best under the paper." },
  { id: 449, delivery: "What’s a snowman’s favorite type of sandwich?", punchline: "Anything on cold cuts." },
  { id: 450, delivery: "What’s a reindeer’s favorite holiday game?", punchline: "Stable tennis." },
  { id: 451, delivery: "Why did Santa fire his weather forecaster?", punchline: "He was always snow wrong." },
  { id: 452, delivery: "Why did Frosty turn down the job offer?", punchline: "It was a temp position." },
  { id: 453, delivery: "Why did the dad refuse to clean the chimney?", punchline: "He said it was beneath him." },
  { id: 454, delivery: "What do you get when you cross Santa with a duck?", punchline: "A Christmas quacker." },
  { id: 455, delivery: "Why do reindeer never get lost?", punchline: "They always follow the star." },
  { id: 456, delivery: "Why did Santa start a landscaping business?", punchline: "He wanted to rake in some green." },
  { id: 457, delivery: "What’s Rudolph’s favorite day of the week?", punchline: "Red-noseday." },
  { id: 458, delivery: "Why did the snowman look in the mirror?", punchline: "To check his ice-solation." },
  { id: 459, delivery: "What do you call Santa when he takes a selfie?", punchline: "Elfie Claus." },
  { id: 460, delivery: "Why did the Christmas lights file a complaint?", punchline: "They were getting burned out." },
  { id: 461, delivery: "What’s Santa’s favorite shape?", punchline: "A snow-hexagon." },
  { id: 462, delivery: "What did Mrs. Claus say when Santa tracked in snow?", punchline: "I told you to wipe your boots, you snow better!" },
  { id: 463, delivery: "Why did the elf wear headphones?", punchline: "He was listening to wrap music." },
  { id: 464, delivery: "What do you call a snowman with a carrot nose and a bad attitude?", punchline: "Rude-olph." },
  { id: 465, delivery: "Why did the candy cane break up with the lollipop?", punchline: "It couldn’t handle the stickiness." },
  { id: 466, delivery: "What do you call a cat sitting on a Christmas present?", punchline: "Santa Claws’ surprise." },
  { id: 467, delivery: "What’s Santa’s favorite plant?", punchline: "Holly-gram." },
  { id: 468, delivery: "What’s a snowman’s favorite song?", punchline: "Ice Ice Baby." },
  { id: 469, delivery: "Why did Santa get kicked out of the karaoke bar?", punchline: "He kept sleighing all the songs." },
  { id: 470, delivery: "What do snowmen take when they’re sick?", punchline: "Chill pills." },
  { id: 471, delivery: "Why did the reindeer start a side hustle?", punchline: "To make some extra dough — deer dough." },
  { id: 472, delivery: "Why did the snowman join social media?", punchline: "He wanted to make cool connections." },
  { id: 473, delivery: "Why was the dad smiling at the credit card bill?", punchline: "He didn’t recognize the man — total denial." },
  { id: 474, delivery: "Why did Santa get new boots?", punchline: "He wanted to sleigh in style." },
  { id: 475, delivery: "What’s a snowman’s favorite cereal?", punchline: "Frosted Mini-Chills." },
  { id: 476, delivery: "Why did the turkey refuse to eat dessert?", punchline: "He was already stuffed — again." },
  { id: 477, delivery: "Why did the Christmas tree go to the dentist?", punchline: "It needed a root canal." },
  { id: 478, delivery: "What did one stocking say to the other?", punchline: "You hang low?" },
  { id: 479, delivery: "Why did Santa use Google Maps?", punchline: "To sleigh in the right direction." },
  { id: 480, delivery: "What do you call Santa when he loses his suit?", punchline: "Saint Knickerless — encore edition." },
  { id: 481, delivery: "What did Frosty say to his friend who melted?", punchline: "“Water shame.”" },
  { id: 482, delivery: "Why did the snowman call in sick?", punchline: "He had the chills." },
  { id: 483, delivery: "What’s Santa’s favorite computer key?", punchline: "The space bar." },
  { id: 484, delivery: "Why did the snowflake go to school?", punchline: "To become a little brighter." },
  { id: 485, delivery: "What do you call Santa’s helpers at the office?", punchline: "Administrative Clauses." },
  { id: 486, delivery: "Why did the snowman take a break?", punchline: "He needed to cool off." },
  { id: 487, delivery: "What’s Santa’s favorite type of workout?", punchline: "Chimney dips." },
  { id: 488, delivery: "Why did Santa’s sleigh stop working?", punchline: "Reindeer malfunction." },
  { id: 489, delivery: "What did Santa say when he lost his sleigh keys?", punchline: "“Oh, deer.”" },
  { id: 490, delivery: "Why did the Christmas cookie cry?", punchline: "It was feeling crumby — again." },
  { id: 491, delivery: "Why did Santa’s hat go missing?", punchline: "He mistle-toed it away." },
  { id: 492, delivery: "What do you get when you cross a snowman with a vampire?", punchline: "Frostbite — eternal classic." },
  { id: 493, delivery: "Why did the reindeer read the newspaper?", punchline: "To stay current." },
  { id: 494, delivery: "Why did the snowman love his new job?", punchline: "He was working in a cool environment." },
  { id: 495, delivery: "Why did Santa’s computer crash?", punchline: "Too many cookies." },
  { id: 496, delivery: "Why did the snowman start meditating?", punchline: "To find his inner peace of ice." },
  { id: 497, delivery: "Why was the snowman’s boss upset?", punchline: "He was flaking on deadlines." },
  { id: 498, delivery: "Why did Santa’s reindeer get detention?", punchline: "Too many flying excuses." },
  { id: 499, delivery: "What’s Santa’s favorite reindeer game?", punchline: "Monopoly — he loves passing snow." },
  { id: 500, delivery: "Why did Santa’s suit wrinkle?", punchline: "Too many Claus in the contract." },
  { id: 501, delivery: "What did Santa say when the elves went on strike?", punchline: "“Yule regret this!”" },
  { id: 502, delivery: "Why did the dad refuse to shovel snow?", punchline: "He said it was beneath him — again." },
  { id: 503, delivery: "Why did the snowman get kicked out of the movie theater?", punchline: "He kept chilling in the aisles." },
  { id: 504, delivery: "Why did the snowman love winter?", punchline: "It was his time to shine." },
  { id: 505, delivery: "What’s Santa’s favorite kind of pasta?", punchline: "Spag-hetti-ho-ho-ho." },
  { id: 506, delivery: "Why did the turkey start a podcast?", punchline: "It had something to gobble about." },
  { id: 507, delivery: "Why did the dad love the snowblower?", punchline: "It gave him a sense of plow-er." },
  { id: 508, delivery: "What’s Santa’s favorite browser?", punchline: "Sleigh-fox." },
  { id: 509, delivery: "Why did the Christmas tree go online?", punchline: "To log in." },
  { id: 510, delivery: "What did the snowman name his pet cat?", punchline: "Frosty Paws." },
  { id: 511, delivery: "Why did Santa get into crypto?", punchline: "He wanted decentralized sleighing." },
  { id: 512, delivery: "Why did the reindeer start a blog?", punchline: "To get more traffic." },
  { id: 513, delivery: "Why was Santa so good at stand-up?", punchline: "He sleighed the crowd." },
  { id: 514, delivery: "Why did the elf get fired?", punchline: "He kept taking elfies on the job." },
  { id: 515, delivery: "Why did the snowman hate summer?", punchline: "It was his downfall." },
  { id: 516, delivery: "Why was the snowflake sad?", punchline: "It fell for the wrong cloud." },
  { id: 517, delivery: "Why did Santa refuse to upgrade his sleigh?", punchline: "He didn’t want to deal with reindeer maintenance." },
  { id: 518, delivery: "What’s Santa’s favorite type of comedy?", punchline: "Slap-Claus." },
  { id: 519, delivery: "Why did the snowman go to therapy?", punchline: "He couldn’t handle the heat." },
  { id: 520, delivery: "What’s a snowman’s favorite movie?", punchline: "Frozen Assets." },
  { id: 521, delivery: "Why did Santa’s belt get promoted?", punchline: "It held everything together." },
  { id: 522, delivery: "Why did the reindeer cross the road?", punchline: "To prove he wasn’t chicken — encore." },
  { id: 523, delivery: "What did Santa say when he lost his GPS?", punchline: "“This is un-deer-livable.”" },
  { id: 524, delivery: "Why did the dad refuse to put up lights this year?", punchline: "He wanted to go dark mode." },
  { id: 525, delivery: "What do you call a reindeer who tells jokes?", punchline: "Pun-dancer." },
  { id: 526, delivery: "Why was Santa’s workshop so noisy?", punchline: "The elves were all a-buzz." },
  { id: 527, delivery: "Why did the dad refuse to get a fake tree?", punchline: "He wanted something more grounded." },
  { id: 528, delivery: "What did the snowman say to the camera?", punchline: "“Freeze!”" },
  { id: 529, delivery: "Why did the cookie go to space?", punchline: "To visit the Milky Way." },
  { id: 530, delivery: "Why was Santa late for work?", punchline: "Slept through his alarm — again." },
  { id: 531, delivery: "Why did Santa buy a treadmill?", punchline: "To keep his Claus in shape." },
  { id: 532, delivery: "Why did the reindeer wear a hat?", punchline: "To cover his bad hair deer." },
  { id: 533, delivery: "Why was Santa’s workshop so efficient?", punchline: "It ran on elf-power." },
  { id: 534, delivery: "Why did Santa love spreadsheets?", punchline: "He liked to sleigh the numbers." },
  { id: 535, delivery: "What did the snowman say to the sun?", punchline: "“You’re my biggest melt.”" },
  { id: 536, delivery: "Why did the dad stay up after midnight on New Year’s Eve?", punchline: "To make sure nothing carried over." },
  { id: 537, delivery: "What did one Christmas light say to the other?", punchline: "“You make me glow.”" },
  { id: 538, delivery: "Why did the snowman get promoted?", punchline: "Cool under pressure." },
  { id: 539, delivery: "Why did the elf bring a pencil to work?", punchline: "To draw attention." },
  { id: 540, delivery: "Why did the snowman take art classes?", punchline: "He wanted to learn how to draw cool lines." },
  { id: 541, delivery: "Why did Santa’s laundry smell funny?", punchline: "He used mistle-soap." },
  { id: 542, delivery: "Why did the dad put the tree up early?", punchline: "He wanted to spruce up the place." },
  { id: 543, delivery: "Why was the reindeer afraid of commitment?", punchline: "He had cold feet." },
  { id: 544, delivery: "What did Santa say when his workshop flooded?", punchline: "“Well, that’s un-elf-fortunate.”" },
  { id: 545, delivery: "Why did the elf go to school?", punchline: "To improve his elf-education." },
  { id: 546, delivery: "Why did the Christmas tree join Twitter?", punchline: "To branch out." },
  { id: 547, delivery: "What’s Santa’s favorite programming language?", punchline: "Ho-ho-HTML." },
  { id: 548, delivery: "Why did the snowman skip the staff meeting?", punchline: "He froze under pressure." },
  { id: 549, delivery: "What do you call a snowman with a carrot in each ear?", punchline: "Anything you want — he can’t hear you." },
  { id: 550, delivery: "Why did Santa start lifting weights?", punchline: "To sleigh the gains." },
  { id: 551, delivery: "What’s Santa’s favorite exercise?", punchline: "Chimney squats." },
  { id: 552, delivery: "Why did the reindeer join the gym?", punchline: "To get fit for takeoff." },
  { id: 553, delivery: "Why did the snowman start a podcast?", punchline: "To talk about cool topics." },
  { id: 554, delivery: "Why did the dad refuse to wear a Christmas sweater?", punchline: "He didn’t want to get into knit-picking." },
  { id: 555, delivery: "Why did the dad stare at the fireplace?", punchline: "He was just reflecting." },
  { id: 556, delivery: "Why did Santa’s sleigh break down again?", punchline: "Bad Claus management." },
  { id: 557, delivery: "Why did the snowman make a TikTok?", punchline: "To go viral — in a chill way." },
  { id: 558, delivery: "Why was Santa’s bag so big?", punchline: "Because he only came once a year." },
  { id: 559, delivery: "Why did the reindeer start a tech startup?", punchline: "To disrupt the sleigh industry." },
  { id: 560, delivery: "Why did the elf become a DJ?", punchline: "He had sick beats." },
  { id: 561, delivery: "Why did the Christmas light go viral?", punchline: "It had a bright personality." },
  { id: 562, delivery: "Why did Santa apply for a loan?", punchline: "He wanted to sleigh his debt." },
  { id: 563, delivery: "What did Santa say to the snowblower?", punchline: "“You blow me away.”" },
  { id: 564, delivery: "Why did the snowman go vegan?", punchline: "He wanted to chill on the ice cream." },
  { id: 565, delivery: "Why did Santa hire accountants?", punchline: "To balance the Claus books." },
  { id: 566, delivery: "What’s a reindeer’s favorite app?", punchline: "Sleighlist." },
  { id: 567, delivery: "Why did the dad love decorating the tree?", punchline: "It was the one time he could truly branch out." },
  { id: 568, delivery: "Why was Santa’s sleigh so noisy?", punchline: "Sleigh bells, ring-a-ding-ding." },
  { id: 569, delivery: "What did the snowman say to the polar bear?", punchline: "“Chill, bro.”" },
  { id: 570, delivery: "Why did the elf get a standing desk?", punchline: "To improve elf posture." },
  { id: 571, delivery: "What’s Santa’s favorite social network?", punchline: "Elf-book." },
  { id: 572, delivery: "Why did Santa get a new iPhone?", punchline: "He wanted better elf-care." },
  { id: 573, delivery: "Why did Frosty take a vacation?", punchline: "He needed to thaw out." },
  { id: 574, delivery: "What’s Santa’s favorite coffee order?", punchline: "A ho-ho-hot latte." },
  { id: 575, delivery: "Why did the reindeer bring a map?", punchline: "To stay on the right path." },
  { id: 576, delivery: "Why was the Christmas party so noisy?", punchline: "Too much wrapping." }
]
