name: super-schema
services:
- name: web
  dockerfile_path: Dockerfile
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  # Runtime environment variables
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: PORT
    value: "8080"
    scope: RUN_AND_BUILD_TIME

  # Build-time environment variables for Vite frontend
  # CRITICAL: These MUST have BUILD_TIME scope to be embedded into client bundle
  # Without BUILD_TIME scope, the client will have 'undefined' for these values
  - key: VITE_CLERK_PUBLISHABLE_KEY
    scope: BUILD_TIME
    type: SECRET
  - key: VITE_STRIPE_PUBLISHABLE_KEY
    scope: BUILD_TIME
    type: SECRET
  - key: VITE_HUBSPOT_CLIENT_ID
    scope: BUILD_TIME
    type: SECRET

  # Server runtime secrets
  - key: CLERK_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: CLERK_WEBHOOK_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: SUPABASE_SERVICE_KEY
    scope: RUN_TIME
    type: SECRET
  - key: STRIPE_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: HUBSPOT_CLIENT_ID
    scope: RUN_TIME
    type: SECRET
  - key: HUBSPOT_CLIENT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: HUBSPOT_ENCRYPTION_KEY
    scope: RUN_TIME
    type: SECRET
